"""
CLI tests for `simforge ligand integrate` — both the original single-ligand
form (--ligand-itp/--ligand-gro) and the new multi-component form
(repeatable --component TOPOLOGY.itp:COORDS.gro).

pdb2gmx is mocked exactly as in ligand/test_integrate.py — no GROMACS
required for this suite.
"""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from unittest.mock import MagicMock, patch

import pytest
from typer.testing import CliRunner

from cli import cli

try:  # click >= 8.2 removed the mix_stderr kwarg (stderr is separate by default)
    runner = CliRunner(mix_stderr=False)
except TypeError:
    runner = CliRunner()

_GMX_WHICH = "ligand.integrate.shutil.which"
_GMX_SUBPROC = "ligand.integrate.subprocess.run"

_MINIMAL_PROTEIN_GRO = dedent("""\
    Protein in water
       5
        1ALA      N    1   1.000   1.000   1.000
        1ALA     CA    2   1.100   1.000   1.000
        1ALA      C    3   1.200   1.000   1.000
        1ALA      O    4   1.250   1.050   1.000
        1ALA     CB    5   1.100   1.100   1.000
       5.00000   5.00000   5.00000
""")

_MASTER_TOPOL_TOP = dedent("""\
    ;
    ; File topol.top was generated by gmx pdb2gmx (master topology)
    ;
    #include "oplsaa.ff/forcefield.itp"

    #include "topol_Protein_chain_A.itp"
    #include "topol_Protein_chain_B.itp"

    ; Include water topology
    #include "oplsaa.ff/spce.itp"

    ; Include topology for ions
    #include "oplsaa.ff/ions.itp"

    [ system ]
    ; Name
    Dimer in water

    [ molecules ]
    ; Compound        #mols
    Protein_chain_A     1
    Protein_chain_B     1
""")

_LIGAND_ITP_WITH_ATOMTYPES = dedent("""\
    ;
    ; GENERATED BY LigParGen Server
    ;
    [ atomtypes ]
      opls_100  C100    12.0110     0.000    A    3.50000E-01   2.76144E-01
      opls_101  O101    15.9990     0.000    A    2.90000E-01   5.85760E-01
    [ moleculetype ]
    ; Name               nrexcl
    E20                 3
    [ atoms ]
    ;   nr       type  resnr residue  atom   cgnr     charge       mass
         1   opls_100      1    E20    C1      1     0.1000    12.0110
         2   opls_101      1    E20    O1      1    -0.2000    15.9990
    [ bonds ]
       1    2    1   1.23000e-01   3.62000e+05
""")

_LIGAND_GRO = dedent("""\
    LIGPARGEN GENERATED GRO FILE
       2
        1E20     C1    1   3.000   3.000   3.000
        1E20     O1    2   3.100   3.000   3.000
       5.00000   5.00000   5.00000
""")

_A1_LIKE_ITP = dedent("""\
    ;
    ; GENERATED BY LigParGen Server
    ;
    [ atomtypes ]
      opls_800  H800     1.0080     0.000    A    2.50000E-01   1.25520E-01
    [ moleculetype ]
    ; Name               nrexcl
    LIG                   3
    [ atoms ]
    ;   nr       type  resnr residue  atom   cgnr     charge       mass
         1   opls_800      1    LIG   H00      1     0.4285     1.0080
""")

def _gro_text(title: str, atoms: list[tuple[str, str, float, float, float]]) -> str:
    """Build a fixed-width .gro text block (same layout as utils.gro_parser.write_gro)."""
    lines = [title, f"{len(atoms):5d}"]
    for i, (resname, atomname, x, y, z) in enumerate(atoms, start=1):
        lines.append(f"{1:5d}{resname:<5s}{atomname:>5s}{i:5d}{x:8.3f}{y:8.3f}{z:8.3f}")
    lines.append("   ".join(f"{v:8.5f}" for v in (5.0, 5.0, 5.0)))
    return "\n".join(lines) + "\n"


_A1_LIKE_GRO = _gro_text("LIGPARGEN GENERATED GRO FILE", [("LIG", "H00", 3.000, 3.000, 3.000)])

_COA_LIKE_ITP = dedent("""\
    ;
    ; GENERATED BY LigParGen Server
    ;
    [ atomtypes ]
      opls_800  N800    14.0070     0.000    A    3.25000E-01   7.11280E-01
    [ moleculetype ]
    ; Name               nrexcl
    COA                   3
    [ atoms ]
    ;   nr       type  resnr residue  atom   cgnr     charge       mass
         1   opls_800      1    COA   N00      1    -0.0954    14.0070
""")

_COA_LIKE_GRO = _gro_text("LIGPARGEN GENERATED GRO FILE", [("COA", "N00", 4.000, 4.000, 4.000)])


def _pdb2gmx_master_write(cmd, **kwargs):
    for flag, content in [
        ("-o", _MINIMAL_PROTEIN_GRO),
        ("-p", _MASTER_TOPOL_TOP),
        ("-i", "; posre\n"),
    ]:
        idx = list(cmd).index(flag)
        Path(cmd[idx + 1]).write_text(content)
    return MagicMock(returncode=0, stdout="", stderr="")


@pytest.fixture()
def gmx_mocked():
    with (
        patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
        patch(_GMX_SUBPROC, side_effect=_pdb2gmx_master_write),
    ):
        yield


class TestIntegrateCmdLegacySingleLigand:
    def test_legacy_invocation_still_works(self, tmp_path, gmx_mocked):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        lig_itp = tmp_path / "LIG.itp"
        lig_itp.write_text(_LIGAND_ITP_WITH_ATOMTYPES)
        lig_gro = tmp_path / "LIG.gro"
        lig_gro.write_text(_LIGAND_GRO)
        out = tmp_path / "system"

        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--ligand-itp", str(lig_itp),
            "--ligand-gro", str(lig_gro),
            "--out", str(out),
            "--no-grompp",
        ])
        assert result.exit_code == 0, result.output
        assert "Assembly complete" in result.output
        assert (out / "ligand_atomtypes.itp").exists()
        assert (out / "topol.top").exists()

    def test_missing_ligand_gro_paired_with_itp_errors(self, tmp_path, gmx_mocked):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        lig_itp = tmp_path / "LIG.itp"
        lig_itp.write_text(_LIGAND_ITP_WITH_ATOMTYPES)

        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--ligand-itp", str(lig_itp),
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "together" in result.output.lower()


class TestIntegrateCmdMultiComponent:
    def test_two_component_invocation_succeeds(self, tmp_path, gmx_mocked):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        a1_itp = tmp_path / "A1.itp"
        a1_itp.write_text(_A1_LIKE_ITP)
        a1_gro = tmp_path / "A1.gro"
        a1_gro.write_text(_A1_LIKE_GRO)
        coa_itp = tmp_path / "COA.itp"
        coa_itp.write_text(_COA_LIKE_ITP)
        coa_gro = tmp_path / "COA.gro"
        coa_gro.write_text(_COA_LIKE_GRO)
        out = tmp_path / "system"

        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--component", f"{a1_itp}:{a1_gro}",
            "--component", f"{coa_itp}:{coa_gro}",
            "--out", str(out),
            "--no-grompp",
        ])
        assert result.exit_code == 0, result.output
        assert "Assembly complete" in result.output
        assert "Parameterized components" in result.output
        assert "A1" in result.output
        assert "COA" in result.output
        assert (out / "component_atomtypes.itp").exists()
        assert (out / "A1.itp").exists()
        assert (out / "COA.itp").exists()

    def test_atomtype_conflict_reported_in_output(self, tmp_path, gmx_mocked):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        a1_itp = tmp_path / "A1.itp"
        a1_itp.write_text(_A1_LIKE_ITP)
        a1_gro = tmp_path / "A1.gro"
        a1_gro.write_text(_A1_LIKE_GRO)
        coa_itp = tmp_path / "COA.itp"
        coa_itp.write_text(_COA_LIKE_ITP)
        coa_gro = tmp_path / "COA.gro"
        coa_gro.write_text(_COA_LIKE_GRO)

        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--component", f"{a1_itp}:{a1_gro}",
            "--component", f"{coa_itp}:{coa_gro}",
            "--out", str(tmp_path / "system"),
            "--no-grompp",
        ])
        assert result.exit_code == 0, result.output
        assert "atomtype conflicts resolved" in result.output
        assert "A1_opls_800" in result.output
        assert "COA_opls_800" in result.output

    def test_mutually_exclusive_flags_rejected(self, tmp_path):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--ligand-itp", "a.itp",
            "--ligand-gro", "a.gro",
            "--component", "b.itp:b.gro",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "mutually exclusive" in result.output.lower()

    def test_no_ligand_or_component_rejected(self, tmp_path):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "provide either" in result.output.lower()

    def test_malformed_component_value_rejected(self, tmp_path):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--component", "no-colon-here",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "TOPOLOGY.itp:COORDS.gro" in result.output

    def test_missing_component_file_rejected(self, tmp_path):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--component", "does_not_exist.itp:does_not_exist.gro",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "not found" in result.output.lower()


# ── Mode B: pre-parameterized protein (--protein-gro/--protein-topology) ───────

_CHAIN_ITP = dedent("""\
    [ moleculetype ]
    Protein_chain_A     3
    [ atoms ]
    1   opls_135      1    ALA   N      1     0.0000    14.0070
    2   opls_135      1    ALA   CA     2     0.0000    12.0110
    3   opls_135      1    ALA   C      3     0.0000    12.0110
    4   opls_135      1    ALA   O      4     0.0000    15.9990
    5   opls_135      1    ALA   CB     5     0.0000    12.0110

    #ifdef POSRES
    #include "posre_Protein_chain_A.itp"
    #endif
""")

_CHAIN_POSRE = "[ position_restraints ]\n1 1 1000 1000 1000\n"


def _protein_only_gro() -> str:
    return _gro_text("Preparameterized protein", [
        ("ALA", "N", 1.000, 1.000, 1.000),
        ("ALA", "CA", 1.100, 1.000, 1.000),
        ("ALA", "C", 1.200, 1.000, 1.000),
        ("ALA", "O", 1.250, 1.050, 1.000),
        ("ALA", "CB", 1.100, 1.100, 1.000),
    ])


class TestIntegrateCmdPreparameterizedProtein:
    def test_preparameterized_never_calls_gmx_subprocess(self, tmp_path):
        gro = tmp_path / "protein_only.gro"
        gro.write_text(_protein_only_gro())
        chain_itp = tmp_path / "topol_Protein_chain_A.itp"
        chain_itp.write_text(_CHAIN_ITP)
        posre = tmp_path / "posre_Protein_chain_A.itp"
        posre.write_text(_CHAIN_POSRE)
        a1_itp = tmp_path / "A1.itp"
        a1_itp.write_text(_A1_LIKE_ITP)
        a1_gro = tmp_path / "A1.gro"
        a1_gro.write_text(_A1_LIKE_GRO)
        coa_itp = tmp_path / "COA.itp"
        coa_itp.write_text(_COA_LIKE_ITP)
        coa_gro = tmp_path / "COA.gro"
        coa_gro.write_text(_COA_LIKE_GRO)
        out = tmp_path / "system"

        with patch(_GMX_SUBPROC) as mock_run:
            result = runner.invoke(cli, [
                "ligand", "integrate",
                "--protein-gro", str(gro),
                "--protein-topology", str(chain_itp),
                "--protein-posre", str(posre),
                "--component", f"{a1_itp}:{a1_gro}",
                "--component", f"{coa_itp}:{coa_gro}",
                "--out", str(out),
                "--no-grompp",
            ])
        assert result.exit_code == 0, result.output
        mock_run.assert_not_called()
        assert "Assembly complete" in result.output
        report = (out / "assembly_report.yaml").read_text()
        assert "protein_input_mode: preparameterized" in report
        assert "pdb2gmx_used: false" in report

    def test_raw_pdb_mode_still_invokes_pdb2gmx(self, tmp_path, gmx_mocked):
        """Regression: --protein (raw) must still go through pdb2gmx."""
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        a1_itp = tmp_path / "A1.itp"
        a1_itp.write_text(_A1_LIKE_ITP)
        a1_gro = tmp_path / "A1.gro"
        a1_gro.write_text(_A1_LIKE_GRO)

        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--component", f"{a1_itp}:{a1_gro}",
            "--out", str(tmp_path / "system"),
            "--no-grompp",
        ])
        assert result.exit_code == 0, result.output
        report = (tmp_path / "system" / "assembly_report.yaml").read_text()
        assert "protein_input_mode: raw_pdb" in report
        assert "pdb2gmx_used: true" in report

    def test_protein_and_protein_gro_mutually_exclusive(self, tmp_path):
        prot = tmp_path / "protein.pdb"
        prot.write_text("END\n")
        gro = tmp_path / "protein.gro"
        gro.write_text(_protein_only_gro())
        chain_itp = tmp_path / "topol_Protein_chain_A.itp"
        chain_itp.write_text(_CHAIN_ITP)

        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein", str(prot),
            "--protein-gro", str(gro),
            "--protein-topology", str(chain_itp),
            "--component", "a.itp:a.gro",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "mutually exclusive" in result.output.lower()

    def test_no_protein_input_rejected(self, tmp_path):
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--component", "a.itp:a.gro",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "provide either" in result.output.lower()

    def test_protein_gro_without_topology_rejected(self, tmp_path):
        gro = tmp_path / "protein.gro"
        gro.write_text(_protein_only_gro())
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein-gro", str(gro),
            "--component", "a.itp:a.gro",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "must be given together" in result.output.lower()

    def test_missing_protein_topology_file_rejected(self, tmp_path):
        gro = tmp_path / "protein.gro"
        gro.write_text(_protein_only_gro())
        result = runner.invoke(cli, [
            "ligand", "integrate",
            "--protein-gro", str(gro),
            "--protein-topology", "does_not_exist.itp",
            "--component", "a.itp:a.gro",
            "--out", str(tmp_path / "system"),
        ])
        assert result.exit_code != 0
        assert "not found" in result.output.lower()
