# builders/step_builders/match_box_builder.py
"""
Builds the match_box_to_bilayer step.

Reads protein_oriented.gro and (when staged) the selected bilayer GRO.
Computes protein bounding box and determines simulation box dimensions.

Phase 3 — bilayer XY authority:
  When a bilayer GRO is staged in membrane_assets/ its box XY dimensions
  are authoritative for the simulation cell.  The protein-derived XY
  (footprint + padding) is used ONLY as a fallback when no bilayer is staged.

  The helper validates that the protein lateral footprint fits inside the
  selected bilayer with a configurable minimum periodic-image margin.
  Failure (protein too large) exits 1 and recommends a larger bilayer patch.

Writes:
  box_match_helper.py  — standalone: reads GROs, computes dimensions,
                          writes box_match_report.json/.md + editconf_cmd.sh
  run.sh               — runs helper then applies editconf_cmd.sh
  metadata.json        — includes gate for box_match_report.json

Lipid parameters and bilayer path are baked into the standalone helper at
compile time so the script needs no SimForge imports at runtime.

Errors (exit 1 from helper → step FAILED → gate blocks downstream):
  - Protein Z extent < 1.0 nm (not membrane-oriented)
  - Protein XY extent > 15 nm (structurally implausible)
  - Protein + 2×margin > bilayer XY (protein too large for selected bilayer)

Warnings (advisory, pipeline continues):
  - Protein XY footprint > 65% of bilayer area (crowded, few surrounding lipids)
  - Protein Z height > 8 nm (very large EC/IC domains)
  - Unknown lipid type (fallback params used)
  - Bilayer GRO not found (falls back to protein-derived XY)
"""

from __future__ import annotations

import json
from pathlib import Path

from core.execution_models import SimulationStep
from core.bilayer_geometry import get_lipid_params


# Token format: str.replace() so Python f-string braces inside the template survive.
# Tokens: {lipid_type}, {bilayer_thickness_nm}, {apl_A2}, {lateral_padding_nm},
#         {solvent_z_padding_nm}, {protein_coverage_warn}, {fallback_used},
#         {bilayer_gro_rel}, {required_margin_nm}, {protein_gro_rel}
_BOX_MATCH_HELPER_TEMPLATE = '''\
#!/usr/bin/env python3
"""
box_match_helper.py — generated by SimForge MatchBoxBuilder.

Phase 3 — bilayer XY authority:
  When BILAYER_GRO_REL points to a staged bilayer GRO, its X/Y box
  dimensions are used as-is for editconf (the bilayer is authoritative).
  Protein-derived XY (footprint + padding) is a fallback only.

Reads protein_oriented.gro (always) and the staged bilayer GRO (when
available). Validates protein fits inside the bilayer with the required
periodic-image margin. Writes box_match_report.json + box_match_report.md
+ editconf_cmd.sh.

Exit code 1 on any error (blocked → gate prevents downstream execution).
"""
import json, sys
from pathlib import Path

LIPID_TYPE              = "{lipid_type}"
BILAYER_THICKNESS_NM    = {bilayer_thickness_nm}
APL_A2                  = {apl_A2}
LATERAL_PADDING_NM      = {lateral_padding_nm}
SOLVENT_Z_PADDING_NM    = {solvent_z_padding_nm}
PROTEIN_COVERAGE_WARN   = {protein_coverage_warn}
FALLBACK_USED           = {fallback_used}
BILAYER_GRO_REL         = "{bilayer_gro_rel}"   # relative path from this script to bilayer GRO
REQUIRED_MARGIN_NM      = {required_margin_nm}   # min periodic-image margin per side (nm)
PROTEIN_GRO_REL         = "{protein_gro_rel}"   # relative path from this script to protein_oriented.gro

MIN_PROTEIN_Z_NM  = 1.0
MAX_PROTEIN_XY_NM = 15.0

_script_dir = Path(__file__).parent


def read_all_positions(gro_path):
    pts = []
    lines = Path(gro_path).read_text().splitlines()
    if len(lines) < 3:
        return pts
    n = int(lines[1].strip())
    for line in lines[2:2 + n]:
        if len(line) < 44:
            continue
        try:
            pts.append((float(line[20:28]), float(line[28:36]), float(line[36:44])))
        except ValueError:
            continue
    return pts


def read_gro_box(gro_path):
    """Return (x_nm, y_nm, z_nm) from GRO box line, or None on any error."""
    try:
        lines = Path(gro_path).read_text().splitlines()
        n = int(lines[1].strip())
        parts = lines[2 + n].split()
        if len(parts) >= 3:
            return float(parts[0]), float(parts[1]), float(parts[2])
    except Exception:
        pass
    return None


# ── Read protein geometry ─────────────────────────────────────────────────────
gro = (_script_dir / PROTEIN_GRO_REL).resolve()
if not gro.exists():
    sys.exit(f"ERROR: protein_oriented.gro not found at {gro} — run orient_protein first.")

pts = read_all_positions(gro)
if len(pts) < 2:
    sys.exit("ERROR: Could not read atom positions from protein_oriented.gro.")

xs = [p[0] for p in pts]
ys = [p[1] for p in pts]
zs = [p[2] for p in pts]

x_min, x_max = min(xs), max(xs)
y_min, y_max = min(ys), max(ys)
z_min, z_max = min(zs), max(zs)

protein_x = x_max - x_min
protein_y = y_max - y_min
protein_z = z_max - z_min

# ── Bilayer box dimensions (authoritative for XY when staged) ─────────────────
bilayer_x = None
bilayer_y = None
bilayer_xy_authority = "protein_derived"
_warn_no_bil = None

if BILAYER_GRO_REL:
    _bil_path = (Path(__file__).parent / BILAYER_GRO_REL).resolve()
    _bil_box  = read_gro_box(_bil_path)
    if _bil_box is not None:
        bilayer_x, bilayer_y, _ = _bil_box
        bilayer_xy_authority = "selected_bilayer"
    else:
        _warn_no_bil = (
            f"Could not read bilayer GRO at \\'{BILAYER_GRO_REL}\\' "
            "— falling back to protein-derived XY. "
            "Run from the correct step directory or re-compile."
        )

# ── Box sizing ────────────────────────────────────────────────────────────────
if bilayer_x is not None:
    # Bilayer is authoritative for XY — use its exact dimensions
    box_x = bilayer_x
    box_y = bilayer_y
else:
    # Fallback: protein footprint + padding (original behaviour)
    box_x = protein_x + 2 * LATERAL_PADDING_NM
    box_y = protein_y + 2 * LATERAL_PADDING_NM
# Z is always protein-aware regardless of XY authority
box_z = BILAYER_THICKNESS_NM + protein_z + 2 * SOLVENT_Z_PADDING_NM

box_area_nm2 = box_x * box_y
box_area_A2  = box_area_nm2 * 100.0
n_lipids_est = int(box_area_A2 / APL_A2 * 2)
coverage     = (protein_x * protein_y) / box_area_nm2

bilayer_vol  = box_x * box_y * BILAYER_THICKNESS_NM
protein_vol  = protein_x * protein_y * protein_z * 0.65
box_vol      = box_x * box_y * box_z
solvent_vol  = max(0.0, box_vol - bilayer_vol - protein_vol)

available_margin_x = (box_x - protein_x) / 2.0
available_margin_y = (box_y - protein_y) / 2.0

errors   = []
warnings = []
checks   = []

# Emit deferred warning when bilayer GRO was requested but not found
if _warn_no_bil is not None:
    warnings.append(_warn_no_bil)

# ── Error: protein Z too small ────────────────────────────────────────────────
if protein_z < MIN_PROTEIN_Z_NM:
    msg = (f"Protein Z extent ({protein_z:.2f} nm < {MIN_PROTEIN_Z_NM} nm). "
           "Structure may not be membrane-oriented — re-check orient_protein output.")
    errors.append(msg)
    checks.append({"name": "protein_z_extent", "passed": False, "message": msg,
                   "value": round(protein_z, 3), "threshold": MIN_PROTEIN_Z_NM})
else:
    checks.append({"name": "protein_z_extent", "passed": True,
                   "message": f"Protein Z extent acceptable ({protein_z:.2f} nm).",
                   "value": round(protein_z, 3), "threshold": MIN_PROTEIN_Z_NM})

# ── Error: protein XY too large ───────────────────────────────────────────────
if protein_x > MAX_PROTEIN_XY_NM or protein_y > MAX_PROTEIN_XY_NM:
    msg = (f"Protein XY footprint ({protein_x:.2f} x {protein_y:.2f} nm) exceeds "
           f"{MAX_PROTEIN_XY_NM} nm — verify structure dimensions.")
    errors.append(msg)
    checks.append({"name": "protein_xy_extent", "passed": False, "message": msg,
                   "value": round(max(protein_x, protein_y), 3),
                   "threshold": MAX_PROTEIN_XY_NM})
else:
    checks.append({"name": "protein_xy_extent", "passed": True,
                   "message": f"Protein XY footprint acceptable ({protein_x:.2f} x {protein_y:.2f} nm).",
                   "value": round(max(protein_x, protein_y), 3),
                   "threshold": MAX_PROTEIN_XY_NM})

# ── Error: protein does not fit inside selected bilayer ───────────────────────
xy_fit_status = "pass"
if bilayer_x is not None:
    fit_fail_x = protein_x + 2 * REQUIRED_MARGIN_NM > bilayer_x
    fit_fail_y = protein_y + 2 * REQUIRED_MARGIN_NM > bilayer_y
    if fit_fail_x or fit_fail_y:
        msg = (
            f"Protein lateral footprint ({protein_x:.2f} \\u00d7 {protein_y:.2f} nm) does not "
            f"fit inside selected bilayer ({bilayer_x:.2f} \\u00d7 {bilayer_y:.2f} nm) with "
            f"the required {REQUIRED_MARGIN_NM:.1f} nm minimum periodic-image margin on each "
            "side. Select a larger bilayer patch or tile the current bilayer. "
            "Bilayer tiling is not yet automated — provide a pre-tiled bilayer file."
        )
        errors.append(msg)
        xy_fit_status = "fail"
        checks.append({
            "name": "xy_fit", "passed": False, "message": msg,
            "required_margin_nm":    REQUIRED_MARGIN_NM,
            "available_margin_x_nm": round(available_margin_x, 3),
            "available_margin_y_nm": round(available_margin_y, 3),
        })
    else:
        checks.append({
            "name": "xy_fit", "passed": True,
            "message": (
                f"Protein fits inside bilayer with "
                f"{available_margin_x:.2f}/{available_margin_y:.2f} nm margin (X/Y)."
            ),
            "required_margin_nm":    REQUIRED_MARGIN_NM,
            "available_margin_x_nm": round(available_margin_x, 3),
            "available_margin_y_nm": round(available_margin_y, 3),
        })

# ── Warning: protein covers too much of box XY ───────────────────────────────
if coverage > PROTEIN_COVERAGE_WARN:
    msg = (f"Protein XY footprint covers {coverage*100:.0f}% of box XY "
           f"(threshold {PROTEIN_COVERAGE_WARN*100:.0f}%). "
           "Limited space for surrounding lipids — consider a larger bilayer patch.")
    warnings.append(msg)
    checks.append({"name": "protein_xy_coverage", "passed": False, "message": msg,
                   "value": round(coverage, 3), "threshold": PROTEIN_COVERAGE_WARN})
else:
    checks.append({"name": "protein_xy_coverage", "passed": True,
                   "message": f"Protein XY coverage acceptable ({coverage*100:.0f}%).",
                   "value": round(coverage, 3), "threshold": PROTEIN_COVERAGE_WARN})

# ── Warning: protein Z very tall ─────────────────────────────────────────────
if protein_z > 8.0:
    msg = (f"Protein Z height is large ({protein_z:.2f} nm). "
           "Ensure box Z ({box_z:.2f} nm) accommodates EC/IC domains with adequate solvent.")
    warnings.append(msg)
    checks.append({"name": "protein_z_tall", "passed": False, "message": msg,
                   "value": round(protein_z, 3), "threshold": 8.0})

# ── Warning: fallback lipid params ───────────────────────────────────────────
if FALLBACK_USED:
    msg = f"Lipid '{LIPID_TYPE}' not in parameter table — using conservative defaults."
    warnings.append(msg)

passed     = len(errors) == 0
penalty    = 0.15 * len(warnings) + 0.35 * len(errors)
confidence = max(0.0, min(1.0, 1.0 - penalty))

report = {
    "lipid_type":       LIPID_TYPE,
    "fallback_used":    FALLBACK_USED,
    "confidence":       round(confidence, 3),
    "passed":           passed,
    "protein_geometry": {
        "x_extent_nm":  round(protein_x, 3),
        "y_extent_nm":  round(protein_y, 3),
        "z_extent_nm":  round(protein_z, 3),
        "x_min_nm":     round(x_min, 3), "x_max_nm": round(x_max, 3),
        "y_min_nm":     round(y_min, 3), "y_max_nm": round(y_max, 3),
        "z_min_nm":     round(z_min, 3), "z_max_nm": round(z_max, 3),
    },
    "recommended_box": {
        "box_x_nm":             round(box_x, 3),
        "box_y_nm":             round(box_y, 3),
        "box_z_nm":             round(box_z, 3),
        "bilayer_thickness_nm": BILAYER_THICKNESS_NM,
        "lateral_padding_nm":   LATERAL_PADDING_NM,
        "solvent_z_padding_nm": SOLVENT_Z_PADDING_NM,
    },
    "bilayer_xy": {
        "bilayer_x_nm":          round(bilayer_x, 3) if bilayer_x is not None else None,
        "bilayer_y_nm":          round(bilayer_y, 3) if bilayer_y is not None else None,
        "xy_authority":          bilayer_xy_authority,
        "required_margin_nm":    REQUIRED_MARGIN_NM,
        "available_margin_x_nm": round(available_margin_x, 3),
        "available_margin_y_nm": round(available_margin_y, 3),
        "xy_fit_status":         xy_fit_status,
    },
    "estimates": {
        "n_lipids_estimate":    n_lipids_est,
        "box_area_nm2":         round(box_area_nm2, 2),
        "box_volume_nm3":       round(box_vol, 2),
        "solvent_volume_nm3":   round(solvent_vol, 2),
        "protein_xy_coverage":  round(coverage, 3),
    },
    "checks":   checks,
    "warnings": warnings,
    "errors":   errors,
}
Path("box_match_report.json").write_text(json.dumps(report, indent=4))

# ── Markdown report ───────────────────────────────────────────────────────────
rb  = report["recommended_box"]
bxy = report["bilayer_xy"]
pg  = report["protein_geometry"]
est = report["estimates"]
status_label = "PASS" if passed else "FAIL"
md = [
    "# Box\\u2013Bilayer Match Report",
    "",
    f"**Lipid:** {LIPID_TYPE}  **Confidence:** {confidence:.2f}  **Status:** {status_label}",
    f"**XY authority:** {bxy['xy_authority']}  **XY fit:** {bxy['xy_fit_status']}",
    "",
    "## Box Dimensions",
    "",
    "| Dimension | Value | Source |",
    "|---|---|---|",
    f"| Box X | {rb['box_x_nm']:.3f} nm | {bxy['xy_authority']} |",
    f"| Box Y | {rb['box_y_nm']:.3f} nm | {bxy['xy_authority']} |",
    f"| Box Z | {rb['box_z_nm']:.3f} nm | protein-aware |",
    f"| Bilayer thickness | {rb['bilayer_thickness_nm']} nm | lipid params |",
    f"| Solvent Z padding (each face) | {rb['solvent_z_padding_nm']} nm | lipid params |",
    "",
    "## Protein Geometry (from protein_oriented.gro)",
    "",
    "| Metric | Value |",
    "|---|---|",
    f"| X extent | {pg['x_extent_nm']:.3f} nm |",
    f"| Y extent | {pg['y_extent_nm']:.3f} nm |",
    f"| Z extent | {pg['z_extent_nm']:.3f} nm |",
    "",
    "## Bilayer XY Fit",
    "",
]
if bxy["bilayer_x_nm"] is not None:
    md += [
        f"- Bilayer X: {bxy['bilayer_x_nm']} nm",
        f"- Bilayer Y: {bxy['bilayer_y_nm']} nm",
    ]
else:
    md += ["- Bilayer: not staged (using protein-derived XY)"]
md += [
    f"- Required margin (each side): {bxy['required_margin_nm']} nm",
    f"- Available margin X: {bxy['available_margin_x_nm']:.3f} nm",
    f"- Available margin Y: {bxy['available_margin_y_nm']:.3f} nm",
    f"- XY fit status: **{bxy['xy_fit_status'].upper()}**",
    "",
    "## Estimates",
    "",
    f"- N lipids both leaflets: **{est['n_lipids_estimate']}**",
    f"- Box XY area: {est['box_area_nm2']:.1f} nm\\u00b2",
    f"- Box volume: {est['box_volume_nm3']:.1f} nm\\u00b3",
    f"- Estimated solvent volume: {est['solvent_volume_nm3']:.1f} nm\\u00b3",
    f"- Protein XY coverage: {est['protein_xy_coverage']*100:.0f}%",
    "",
    "## Checks",
    "",
]
for c in checks:
    icon = "\\u2705" if c["passed"] else "\\u274c"
    md.append(f"{icon} {c['message']}")
md += ["", "## Warnings", ""]
md += [f"\\u26a0\\ufe0f  {w}" for w in warnings] if warnings else ["_None_"]
md += ["", "## Errors", ""]
md += [f"\\u274c  {e}" for e in errors] if errors else ["_None_"]
md += ["", "---", "_Generated by SimForge MatchBoxBuilder_"]
Path("box_match_report.md").write_text("\\n".join(md))

# ── editconf command — uses bilayer XY when authoritative ─────────────────────
# Use absolute path for -f so editconf_cmd.sh works regardless of CWD.
Path("editconf_cmd.sh").write_text(
    f"gmx editconf -f {str(gro)} -o protein_boxed.gro "
    f"-box {rb['box_x_nm']:.3f} {rb['box_y_nm']:.3f} {rb['box_z_nm']:.3f} -c\\n"
)

print(f"Protein:  {pg['x_extent_nm']:.2f} x {pg['y_extent_nm']:.2f} x {pg['z_extent_nm']:.2f} nm")
print(f"Box XY:   {rb['box_x_nm']:.3f} x {rb['box_y_nm']:.3f} nm  [{bilayer_xy_authority}]")
print(f"Box Z:    {rb['box_z_nm']:.3f} nm  [protein-aware]")
print(f"Margin:   {available_margin_x:.3f} x {available_margin_y:.3f} nm (X/Y)  [{xy_fit_status}]")
print(f"N lipids estimate: {est['n_lipids_estimate']}  (XY coverage: {est['protein_xy_coverage']*100:.0f}%)")
print(f"Confidence: {confidence:.2f}  [{status_label}]")
for w in warnings:
    print(f"  WARNING: {w}")
for e_msg in errors:
    print(f"  ERROR: {e_msg}")
print("Written: box_match_report.json, box_match_report.md, editconf_cmd.sh")

if errors:
    sys.exit(1)
'''


class MatchBoxBuilder:
    """
    Builds the match_box_to_bilayer step.

    Generates a fully automated step: box_match_helper.py computes the
    geometry from protein_oriented.gro (and the staged bilayer GRO when
    available), then run.sh applies it with editconf.

    Phase 3: when __membrane_assets__ is in step_dir_map and bilayer_file
    is in step.params, the bilayer GRO path is baked into the helper so
    its box XY dimensions become authoritative for the simulation cell.

    Phase 8A: when adaptive_registration is True, generates
    run_membrane_registration.py which searches bilayer Z shifts before
    embed_in_bilayer and writes membrane_registration_report.json.
    """

    def build(
        self,
        step:         SimulationStep,
        step_dir:     Path,
        step_dir_map: dict = {},
    ) -> None:
        lipid_type = step.params.get("lipid", "DPPC").upper()
        params, fallback = get_lipid_params(lipid_type)

        # ── Bilayer GRO path (baked into helper for runtime XY authority) ────
        bilayer_file        = step.params.get("bilayer_file", "dppc512_whole.gro")
        required_margin_nm  = float(step.params.get("required_margin_nm", 1.0))
        membrane_assets_dir = step_dir_map.get("__membrane_assets__")

        if membrane_assets_dir is not None:
            from builders.step_builders._utils import rel as _rel
            assets_rel      = _rel(step_dir, Path(membrane_assets_dir))
            bilayer_gro_rel = f"{assets_rel}/{bilayer_file}"
        else:
            bilayer_gro_rel = ""   # no bilayer staged → helper falls back to protein-derived XY

        # ── protein_oriented.gro path (cross-step reference) ────────────────
        orient_dir = step_dir_map.get("orient_protein")
        if orient_dir is not None:
            from builders.step_builders._utils import rel as _rel
            protein_gro_rel = f"{_rel(step_dir, Path(orient_dir))}/protein_oriented.gro"
        else:
            protein_gro_rel = "protein_oriented.gro"  # fallback: same dir (tests/legacy)

        helper_code = (
            _BOX_MATCH_HELPER_TEMPLATE
            .replace("{lipid_type}",            lipid_type)
            .replace("{bilayer_thickness_nm}",  str(params.bilayer_thickness_nm))
            .replace("{apl_A2}",                str(params.apl_A2))
            .replace("{lateral_padding_nm}",    str(params.lateral_padding_nm))
            .replace("{solvent_z_padding_nm}",  str(params.solvent_z_padding_nm))
            .replace("{protein_coverage_warn}", str(params.protein_coverage_warn))
            .replace("{fallback_used}",         repr(fallback))
            .replace("{bilayer_gro_rel}",       bilayer_gro_rel)
            .replace("{required_margin_nm}",    str(required_margin_nm))
            .replace("{protein_gro_rel}",       protein_gro_rel)
        )
        (step_dir / "box_match_helper.py").write_text(helper_code)

        # ── Phase 8A: Adaptive membrane registration ─────────────────────────
        adaptive_registration  = bool(step.params.get("adaptive_registration", False))
        reg_search_min         = float(step.params.get("reg_search_min_nm", -1.5))
        reg_search_max         = float(step.params.get("reg_search_max_nm",  1.5))
        reg_search_step        = float(step.params.get("reg_search_step_nm", 0.1))
        reg_policy             = str(step.params.get("reg_policy", "warn"))
        reg_max_allowed_shift  = float(step.params.get("reg_max_allowed_shift_nm", 1.5))
        reg_hc_half_thickness  = float(step.params.get("reg_hydrophobic_half_thickness_nm", 1.25))
        # Phase 8B: Surface-interference registration
        reg_hg_thickness       = float(step.params.get("reg_headgroup_thickness_nm", 0.5))

        # TM / EC / IC residue sets (baked from structural_annotation)
        tm_residues_str = step.params.get("tm_residues")
        ec_residues_str = step.params.get("ec_residues")
        ic_residues_str = step.params.get("ic_residues")

        if tm_residues_str:
            from core.structural_annotation import residues_in_range
            tm_set_val = f"set({sorted(residues_in_range(tm_residues_str))!r})"
        else:
            tm_set_val = "None"

        if ec_residues_str:
            from core.structural_annotation import residues_in_range
            ec_set_val = f"set({sorted(residues_in_range(ec_residues_str))!r})"
        else:
            ec_set_val = "set()"

        if ic_residues_str:
            from core.structural_annotation import residues_in_range
            ic_set_val = f"set({sorted(residues_in_range(ic_residues_str))!r})"
        else:
            ic_set_val = "set()"

        simforge_root = str(Path(__file__).resolve().parent.parent.parent)

        # Always generate the registration script; it writes a disabled/no-TM
        # report when not applicable so the embed step can always find the file.
        reg_script = f'''#!/usr/bin/env python3
"""
run_membrane_registration.py — generated by SimForge MatchBoxBuilder (Phase 8A).
Searches bilayer Z shifts to maximise TM burial before embed_in_bilayer.
Writes membrane_registration_report.json in this step directory.
"""
import sys, json
from pathlib import Path

sys.path.insert(0, {simforge_root!r})

from validators.membrane_registration import adaptive_membrane_registration

SCRIPT_DIR = Path(__file__).parent.resolve()

ADAPTIVE_REGISTRATION   = {adaptive_registration}
SEARCH_MIN_NM           = {reg_search_min}
SEARCH_MAX_NM           = {reg_search_max}
SEARCH_STEP_NM          = {reg_search_step}
POLICY                  = {reg_policy!r}
MAX_ALLOWED_SHIFT_NM    = {reg_max_allowed_shift}
HC_HALF_THICKNESS_NM    = {reg_hc_half_thickness}

TM_RESIDUES = {tm_set_val}
EC_RESIDUES = {ec_set_val}
IC_RESIDUES = {ic_set_val}

PROTEIN_GRO_REL = 'protein_boxed.gro'   # produced by editconf_cmd.sh in this same step
BILAYER_GRO_REL = {bilayer_gro_rel!r}

if not ADAPTIVE_REGISTRATION or TM_RESIDUES is None:
    report = {{
        "enabled": False,
        "selected_shift_z_nm": 0.0,
        "actual_z_shift_nm": None,
        "initial_tm_center_z": None,
        "initial_bilayer_midplane_z": None,
        "final_bilayer_midplane_z": None,
        "search_range_nm": [SEARCH_MIN_NM, SEARCH_MAX_NM],
        "search_step_nm": SEARCH_STEP_NM,
        "candidates": [],
        "best_candidate": None,
        "score_components": {{}},
        "tm_burial_fraction": None,
        "tm_ca_burial_fraction": None,
        "soluble_domain_core_penetration_fraction": None,
        "non_tm_core_atom_count": None,
        "ec_core_atom_count": None,
        "ic_core_atom_count": None,
        "expected_void_risk_score": None,
        "decision_reason": "Adaptive registration disabled or no TM annotation",
        "warnings": [],
    }}
    (SCRIPT_DIR / "membrane_registration_report.json").write_text(json.dumps(report, indent=2))
    print("[membrane_registration] Disabled — using default TM-centre alignment")
    sys.exit(0)

protein_gro = (SCRIPT_DIR / PROTEIN_GRO_REL).resolve()
bilayer_gro = (SCRIPT_DIR / BILAYER_GRO_REL).resolve() if BILAYER_GRO_REL else None

if not protein_gro.exists():
    print(f"WARNING: protein_gro not found at {{protein_gro}} — skipping registration", file=sys.stderr)
    report = {{
        "enabled": False, "selected_shift_z_nm": 0.0, "actual_z_shift_nm": None,
        "initial_tm_center_z": None, "initial_bilayer_midplane_z": None,
        "final_bilayer_midplane_z": None, "candidates": [], "best_candidate": None,
        "decision_reason": f"protein_gro not found: {{protein_gro}}", "warnings": [],
    }}
    (SCRIPT_DIR / "membrane_registration_report.json").write_text(json.dumps(report, indent=2))
    sys.exit(0)

if bilayer_gro is None or not bilayer_gro.exists():
    print(f"WARNING: bilayer_gro not found — skipping registration", file=sys.stderr)
    report = {{
        "enabled": False, "selected_shift_z_nm": 0.0, "actual_z_shift_nm": None,
        "initial_tm_center_z": None, "initial_bilayer_midplane_z": None,
        "final_bilayer_midplane_z": None, "candidates": [], "best_candidate": None,
        "decision_reason": "bilayer_gro not found", "warnings": [],
    }}
    (SCRIPT_DIR / "membrane_registration_report.json").write_text(json.dumps(report, indent=2))
    sys.exit(0)

report = adaptive_membrane_registration(
    protein_gro             = protein_gro,
    bilayer_gro             = bilayer_gro,
    tm_residues             = TM_RESIDUES,
    ec_residues             = EC_RESIDUES,
    ic_residues             = IC_RESIDUES,
    search_min_nm           = SEARCH_MIN_NM,
    search_max_nm           = SEARCH_MAX_NM,
    search_step_nm          = SEARCH_STEP_NM,
    hydrophobic_half_thickness_nm = HC_HALF_THICKNESS_NM,
    policy                  = POLICY,
    max_allowed_shift_nm    = MAX_ALLOWED_SHIFT_NM,
    output_dir              = SCRIPT_DIR,
)

blocked = report.get("blocked", False)
shift   = report.get("selected_shift_z_nm", 0.0)
reason  = report.get("decision_reason", "")
print(f"[membrane_registration] selected_shift_z_nm={{shift:+.3f}} nm — {{reason}}")
for w in report.get("warnings", []):
    print(f"[membrane_registration] WARNING: {{w}}")

if blocked and POLICY == "strict":
    print(f"ERROR: Adaptive registration blocked (policy=strict): {{reason}}", file=sys.stderr)
    sys.exit(1)

n_cand = len(report.get("candidates", []))
print(f"[membrane_registration] Evaluated {{n_cand}} candidates — report: membrane_registration_report.json")
'''
        (step_dir / "run_membrane_registration.py").write_text(reg_script)

        # ── Phase 8B: Surface-interference registration script ─────────────────
        surf_reg_script = f'''#!/usr/bin/env python3
"""
run_membrane_surface_registration.py — generated by SimForge MatchBoxBuilder (Phase 8B).
Extends Phase 8A: penalises EC/IC/loop interference with bilayer headgroup surfaces.
Writes membrane_surface_registration_report.json in this step directory.
Phase 8B shift takes precedence over Phase 8A in embed_in_bilayer.
"""
import sys, json
from pathlib import Path

sys.path.insert(0, {simforge_root!r})

from validators.membrane_surface_registration import surface_interference_adaptive_registration

SCRIPT_DIR = Path(__file__).parent.resolve()

ADAPTIVE_REGISTRATION   = {adaptive_registration}
SEARCH_MIN_NM           = {reg_search_min}
SEARCH_MAX_NM           = {reg_search_max}
SEARCH_STEP_NM          = {reg_search_step}
POLICY                  = {reg_policy!r}
MAX_ALLOWED_SHIFT_NM    = {reg_max_allowed_shift}
HC_HALF_THICKNESS_NM    = {reg_hc_half_thickness}
HG_THICKNESS_NM         = {reg_hg_thickness}

TM_RESIDUES = {tm_set_val}
EC_RESIDUES = {ec_set_val}
IC_RESIDUES = {ic_set_val}

PROTEIN_GRO_REL = 'protein_boxed.gro'
BILAYER_GRO_REL = {bilayer_gro_rel!r}

if not ADAPTIVE_REGISTRATION or TM_RESIDUES is None:
    report = {{
        "enabled": False, "phase": "8B",
        "selected_shift_z_nm": 0.0, "actual_z_shift_nm": None,
        "decision_reason": "Phase 8B disabled or no TM annotation",
        "warnings": [],
    }}
    (SCRIPT_DIR / "membrane_surface_registration_report.json").write_text(json.dumps(report, indent=2))
    print("[surface_registration] Disabled — skipping Phase 8B")
    sys.exit(0)

protein_gro = (SCRIPT_DIR / PROTEIN_GRO_REL).resolve()
bilayer_gro = (SCRIPT_DIR / BILAYER_GRO_REL).resolve() if BILAYER_GRO_REL else None

if not protein_gro.exists() or bilayer_gro is None or not bilayer_gro.exists():
    report = {{
        "enabled": False, "phase": "8B",
        "selected_shift_z_nm": 0.0, "actual_z_shift_nm": None,
        "decision_reason": "Input GRO not found — Phase 8B skipped",
        "warnings": ["protein_boxed.gro or bilayer GRO not found"],
    }}
    (SCRIPT_DIR / "membrane_surface_registration_report.json").write_text(json.dumps(report, indent=2))
    sys.exit(0)

report = surface_interference_adaptive_registration(
    protein_gro                 = protein_gro,
    bilayer_gro                 = bilayer_gro,
    tm_residues                 = TM_RESIDUES,
    ec_residues                 = EC_RESIDUES,
    ic_residues                 = IC_RESIDUES,
    search_min_nm               = SEARCH_MIN_NM,
    search_max_nm               = SEARCH_MAX_NM,
    search_step_nm              = SEARCH_STEP_NM,
    hydrophobic_half_thickness_nm = HC_HALF_THICKNESS_NM,
    headgroup_thickness_nm      = HG_THICKNESS_NM,
    policy                      = POLICY,
    max_allowed_shift_nm        = MAX_ALLOWED_SHIFT_NM,
    output_dir                  = SCRIPT_DIR,
)

shift  = report.get("selected_shift_z_nm", 0.0)
reason = report.get("decision_reason", "")
print(f"[surface_registration] selected_shift_z_nm={{shift:+.3f}} nm — {{reason}}")
for w in report.get("warnings", []):
    print(f"[surface_registration] WARNING: {{w}}")

n_cand = len(report.get("candidates", []))
print(f"[surface_registration] Evaluated {{n_cand}} candidates — report: membrane_surface_registration_report.json")

if report.get("blocked") and POLICY == "strict":
    print(f"ERROR: Phase 8B registration blocked: {{reason}}", file=sys.stderr)
    sys.exit(1)
'''
        (step_dir / "run_membrane_surface_registration.py").write_text(surf_reg_script)

        # ── run.sh ────────────────────────────────────────────────────────────
        run_sh = """\
#!/bin/bash
# ─── match_box_to_bilayer (automatic) ────────────────────────────────────────
# Step 1: compute recommended box from protein_oriented.gro (+ bilayer GRO)
python3 box_match_helper.py

# Step 2: apply computed box dimensions — produces protein_boxed.gro
bash editconf_cmd.sh

# Step 3: adaptive membrane registration (Phase 8A — TM burial focus)
# Reads protein_boxed.gro — writes membrane_registration_report.json
python3 run_membrane_registration.py

# Step 4: surface-interference registration (Phase 8B — EC/IC/loop surface penalty)
# Writes membrane_surface_registration_report.json (takes precedence over Phase 8A in embed)
python3 run_membrane_surface_registration.py
"""
        (step_dir / "run.sh").write_text(run_sh)

        expected_outputs = [
            "box_match_report.json",
            "box_match_report.md",
            "editconf_cmd.sh",
            "protein_boxed.gro",
            "membrane_registration_report.json",
            "membrane_surface_registration_report.json",
        ]

        (step_dir / "metadata.json").write_text(json.dumps({
            "step_id":            step.step_id,
            "stage":              step.stage.value,
            "engine":             step.engine,
            "step_type":          "automatic",
            "automation_level":   "automated",
            "lipid_type":         lipid_type,
            "fallback_used":      fallback,
            "bilayer_file":       bilayer_file,
            "bilayer_gro_rel":    bilayer_gro_rel,
            "protein_gro_rel":    protein_gro_rel,
            "required_margin_nm": required_margin_nm,
            "adaptive_registration": adaptive_registration,
            "registration": {
                "search_min_nm":           reg_search_min,
                "search_max_nm":           reg_search_max,
                "search_step_nm":          reg_search_step,
                "policy":                  reg_policy,
                "max_allowed_shift_nm":    reg_max_allowed_shift,
                "hydrophobic_half_thickness_nm": reg_hc_half_thickness,
            },
            "lipid_params": {
                "bilayer_thickness_nm":  params.bilayer_thickness_nm,
                "apl_A2":                params.apl_A2,
                "lateral_padding_nm":    params.lateral_padding_nm,
                "solvent_z_padding_nm":  params.solvent_z_padding_nm,
                "protein_coverage_warn": params.protein_coverage_warn,
            },
            "expected_outputs": expected_outputs,
            "gate": {
                "artifact": "box_match_report.json",
                "type":     "box_match_report",
            },
        }, indent=4))
