# builders/step_builders/match_box_builder.py
"""
Builds the match_box_to_bilayer step.

Reads protein_oriented.gro, computes protein bounding box and recommended
bilayer box dimensions from lipid physical constants.  Writes:
  box_match_helper.py  — standalone: reads GRO, computes recommendation,
                          writes box_match_report.json/.md + editconf_cmd.sh
  run.sh               — runs helper then applies editconf_cmd.sh
  metadata.json        — includes gate for box_match_report.json

Lipid parameters are baked into the standalone helper at compile time
so the script needs no SimForge imports at runtime.

Errors (exit 1 from helper → step FAILED → gate blocks downstream):
  - Protein Z extent < 1.0 nm (not membrane-oriented)
  - Protein XY extent > 15 nm (structurally implausible)

Warnings (advisory, pipeline continues):
  - Protein XY footprint > 65% of recommended box
  - Protein Z height > 8 nm (very large EC/IC domains)
  - Unknown lipid type (fallback params used)
"""

from __future__ import annotations

import json
from pathlib import Path

from core.execution_models import SimulationStep
from core.bilayer_geometry import get_lipid_params


# Token format: str.replace() so Python f-string braces inside the template survive.
# Tokens: {lipid_type}, {bilayer_thickness_nm}, {apl_A2}, {lateral_padding_nm},
#         {solvent_z_padding_nm}, {protein_coverage_warn}, {fallback_used}
_BOX_MATCH_HELPER_TEMPLATE = '''\
#!/usr/bin/env python3
"""
box_match_helper.py — generated by SimForge MatchBoxBuilder.
Reads protein_oriented.gro, computes protein bounding box and recommended
bilayer box dimensions. Writes box_match_report.json + box_match_report.md
+ editconf_cmd.sh.

Exit code 1 when protein dimensions are clearly incompatible with a
membrane-oriented structure (errors). Warnings do not trigger failure.
"""
import json, sys
from pathlib import Path

LIPID_TYPE              = "{lipid_type}"
BILAYER_THICKNESS_NM    = {bilayer_thickness_nm}
APL_A2                  = {apl_A2}
LATERAL_PADDING_NM      = {lateral_padding_nm}
SOLVENT_Z_PADDING_NM    = {solvent_z_padding_nm}
PROTEIN_COVERAGE_WARN   = {protein_coverage_warn}
FALLBACK_USED           = {fallback_used}

MIN_PROTEIN_Z_NM = 1.0
MAX_PROTEIN_XY_NM = 15.0


def read_all_positions(gro_path):
    pts = []
    lines = Path(gro_path).read_text().splitlines()
    if len(lines) < 3:
        return pts
    n = int(lines[1].strip())
    for line in lines[2:2 + n]:
        if len(line) < 44:
            continue
        try:
            pts.append((float(line[20:28]), float(line[28:36]), float(line[36:44])))
        except ValueError:
            continue
    return pts


gro = Path("protein_oriented.gro")
if not gro.exists():
    sys.exit("ERROR: protein_oriented.gro not found — run orient_protein first.")

pts = read_all_positions(gro)
if len(pts) < 2:
    sys.exit("ERROR: Could not read atom positions from protein_oriented.gro.")

xs = [p[0] for p in pts]
ys = [p[1] for p in pts]
zs = [p[2] for p in pts]

x_min, x_max = min(xs), max(xs)
y_min, y_max = min(ys), max(ys)
z_min, z_max = min(zs), max(zs)

protein_x = x_max - x_min
protein_y = y_max - y_min
protein_z = z_max - z_min

box_x = protein_x + 2 * LATERAL_PADDING_NM
box_y = protein_y + 2 * LATERAL_PADDING_NM
box_z = BILAYER_THICKNESS_NM + protein_z + 2 * SOLVENT_Z_PADDING_NM

box_area_nm2  = box_x * box_y
box_area_A2   = box_area_nm2 * 100.0
n_lipids_est  = int(box_area_A2 / APL_A2 * 2)

coverage      = (protein_x * protein_y) / box_area_nm2

bilayer_vol   = box_x * box_y * BILAYER_THICKNESS_NM
protein_vol   = protein_x * protein_y * protein_z * 0.65
box_vol       = box_x * box_y * box_z
solvent_vol   = max(0.0, box_vol - bilayer_vol - protein_vol)

errors   = []
warnings = []
checks   = []

# ── Error: protein Z too small ────────────────────────────────────────────────
if protein_z < MIN_PROTEIN_Z_NM:
    msg = (f"Protein Z extent ({protein_z:.2f} nm < {MIN_PROTEIN_Z_NM} nm). "
           "Structure may not be membrane-oriented — re-check orient_protein output.")
    errors.append(msg)
    checks.append({"name": "protein_z_extent", "passed": False, "message": msg,
                   "value": round(protein_z, 3), "threshold": MIN_PROTEIN_Z_NM})
else:
    checks.append({"name": "protein_z_extent", "passed": True,
                   "message": f"Protein Z extent acceptable ({protein_z:.2f} nm).",
                   "value": round(protein_z, 3), "threshold": MIN_PROTEIN_Z_NM})

# ── Error: protein XY too large ───────────────────────────────────────────────
if protein_x > MAX_PROTEIN_XY_NM or protein_y > MAX_PROTEIN_XY_NM:
    msg = (f"Protein XY footprint ({protein_x:.2f} x {protein_y:.2f} nm) exceeds "
           f"{MAX_PROTEIN_XY_NM} nm — verify structure dimensions.")
    errors.append(msg)
    checks.append({"name": "protein_xy_extent", "passed": False, "message": msg,
                   "value": round(max(protein_x, protein_y), 3),
                   "threshold": MAX_PROTEIN_XY_NM})
else:
    checks.append({"name": "protein_xy_extent", "passed": True,
                   "message": f"Protein XY footprint acceptable ({protein_x:.2f} x {protein_y:.2f} nm).",
                   "value": round(max(protein_x, protein_y), 3),
                   "threshold": MAX_PROTEIN_XY_NM})

# ── Warning: protein covers too much of box XY ───────────────────────────────
if coverage > PROTEIN_COVERAGE_WARN:
    msg = (f"Protein XY footprint covers {coverage*100:.0f}% of box XY "
           f"(threshold {PROTEIN_COVERAGE_WARN*100:.0f}%). "
           "Limited space for surrounding lipids — consider a larger bilayer patch.")
    warnings.append(msg)
    checks.append({"name": "protein_xy_coverage", "passed": False, "message": msg,
                   "value": round(coverage, 3), "threshold": PROTEIN_COVERAGE_WARN})
else:
    checks.append({"name": "protein_xy_coverage", "passed": True,
                   "message": f"Protein XY coverage acceptable ({coverage*100:.0f}%).",
                   "value": round(coverage, 3), "threshold": PROTEIN_COVERAGE_WARN})

# ── Warning: protein Z very tall ─────────────────────────────────────────────
if protein_z > 8.0:
    msg = (f"Protein Z height is large ({protein_z:.2f} nm). "
           "Ensure box Z ({box_z:.2f} nm) accommodates EC/IC domains with adequate solvent.")
    warnings.append(msg)
    checks.append({"name": "protein_z_tall", "passed": False, "message": msg,
                   "value": round(protein_z, 3), "threshold": 8.0})

# ── Warning: fallback lipid params ───────────────────────────────────────────
if FALLBACK_USED:
    msg = f"Lipid '{LIPID_TYPE}' not in parameter table — using conservative defaults."
    warnings.append(msg)

passed     = len(errors) == 0
penalty    = 0.15 * len(warnings) + 0.35 * len(errors)
confidence = max(0.0, min(1.0, 1.0 - penalty))

report = {
    "lipid_type":       LIPID_TYPE,
    "fallback_used":    FALLBACK_USED,
    "confidence":       round(confidence, 3),
    "passed":           passed,
    "protein_geometry": {
        "x_extent_nm":  round(protein_x, 3),
        "y_extent_nm":  round(protein_y, 3),
        "z_extent_nm":  round(protein_z, 3),
        "x_min_nm":     round(x_min, 3), "x_max_nm": round(x_max, 3),
        "y_min_nm":     round(y_min, 3), "y_max_nm": round(y_max, 3),
        "z_min_nm":     round(z_min, 3), "z_max_nm": round(z_max, 3),
    },
    "recommended_box": {
        "box_x_nm":             round(box_x, 3),
        "box_y_nm":             round(box_y, 3),
        "box_z_nm":             round(box_z, 3),
        "bilayer_thickness_nm": BILAYER_THICKNESS_NM,
        "lateral_padding_nm":   LATERAL_PADDING_NM,
        "solvent_z_padding_nm": SOLVENT_Z_PADDING_NM,
    },
    "estimates": {
        "n_lipids_estimate":    n_lipids_est,
        "box_area_nm2":         round(box_area_nm2, 2),
        "box_volume_nm3":       round(box_vol, 2),
        "solvent_volume_nm3":   round(solvent_vol, 2),
        "protein_xy_coverage":  round(coverage, 3),
    },
    "checks":   checks,
    "warnings": warnings,
    "errors":   errors,
}
Path("box_match_report.json").write_text(json.dumps(report, indent=4))

# ── Markdown report ───────────────────────────────────────────────────────────
rb  = report["recommended_box"]
pg  = report["protein_geometry"]
est = report["estimates"]
status_label = "PASS" if passed else "FAIL"
md = [
    "# Box–Bilayer Match Report",
    "",
    f"**Lipid:** {LIPID_TYPE}  **Confidence:** {confidence:.2f}  **Status:** {status_label}",
    "",
    "## Recommended Box",
    "",
    "| Dimension | Value |",
    "|---|---|",
    f"| Box X | {rb['box_x_nm']:.3f} nm |",
    f"| Box Y | {rb['box_y_nm']:.3f} nm |",
    f"| Box Z | {rb['box_z_nm']:.3f} nm |",
    f"| Bilayer thickness | {rb['bilayer_thickness_nm']} nm |",
    f"| Lateral padding (each side) | {rb['lateral_padding_nm']} nm |",
    f"| Solvent Z padding (each face) | {rb['solvent_z_padding_nm']} nm |",
    "",
    "## Protein Geometry (from protein_oriented.gro)",
    "",
    "| Metric | Value |",
    "|---|---|",
    f"| X extent | {pg['x_extent_nm']:.3f} nm |",
    f"| Y extent | {pg['y_extent_nm']:.3f} nm |",
    f"| Z extent | {pg['z_extent_nm']:.3f} nm |",
    "",
    "## Estimates",
    "",
    f"- N lipids both leaflets: **{est['n_lipids_estimate']}**",
    f"- Box XY area: {est['box_area_nm2']:.1f} nm²",
    f"- Box volume: {est['box_volume_nm3']:.1f} nm³",
    f"- Estimated solvent volume: {est['solvent_volume_nm3']:.1f} nm³",
    f"- Protein XY coverage: {est['protein_xy_coverage']*100:.0f}%",
    "",
    "## Checks",
    "",
]
for c in checks:
    icon = "\\u2705" if c["passed"] else "\\u274c"
    md.append(f"{icon} {c['message']}")
md += ["", "## Warnings", ""]
md += [f"\\u26a0\\ufe0f  {w}" for w in warnings] if warnings else ["_None_"]
md += ["", "## Errors", ""]
md += [f"\\u274c  {e}" for e in errors] if errors else ["_None_"]
md += ["", "---", "_Generated by SimForge MatchBoxBuilder_"]
Path("box_match_report.md").write_text("\\n".join(md))

# ── editconf command ──────────────────────────────────────────────────────────
Path("editconf_cmd.sh").write_text(
    f"gmx editconf -f protein_oriented.gro -o protein_boxed.gro "
    f"-box {rb['box_x_nm']:.3f} {rb['box_y_nm']:.3f} {rb['box_z_nm']:.3f} -c\\n"
)

print(f"Protein:  {pg['x_extent_nm']:.2f} x {pg['y_extent_nm']:.2f} x {pg['z_extent_nm']:.2f} nm")
print(f"Box:      {rb['box_x_nm']:.3f} x {rb['box_y_nm']:.3f} x {rb['box_z_nm']:.3f} nm")
print(f"N lipids estimate: {est['n_lipids_estimate']}  (XY coverage: {est['protein_xy_coverage']*100:.0f}%)")
print(f"Confidence: {confidence:.2f}  [{status_label}]")
for w in warnings:
    print(f"  WARNING: {w}")
for e_msg in errors:
    print(f"  ERROR: {e_msg}")
print("Written: box_match_report.json, box_match_report.md, editconf_cmd.sh")

if errors:
    sys.exit(1)
'''


class MatchBoxBuilder:
    """
    Builds the match_box_to_bilayer step.

    Generates a fully automated step: box_match_helper.py computes the
    geometry from protein_oriented.gro, then run.sh applies it with editconf.
    """

    def build(
        self,
        step:         SimulationStep,
        step_dir:     Path,
        step_dir_map: dict = {},
    ) -> None:
        lipid_type = step.params.get("lipid", "DPPC").upper()
        params, fallback = get_lipid_params(lipid_type)

        helper_code = (
            _BOX_MATCH_HELPER_TEMPLATE
            .replace("{lipid_type}",            lipid_type)
            .replace("{bilayer_thickness_nm}",  str(params.bilayer_thickness_nm))
            .replace("{apl_A2}",                str(params.apl_A2))
            .replace("{lateral_padding_nm}",    str(params.lateral_padding_nm))
            .replace("{solvent_z_padding_nm}",  str(params.solvent_z_padding_nm))
            .replace("{protein_coverage_warn}", str(params.protein_coverage_warn))
            .replace("{fallback_used}",         repr(fallback))
        )
        (step_dir / "box_match_helper.py").write_text(helper_code)

        run_sh = """\
#!/bin/bash
# ─── match_box_to_bilayer (automatic) ────────────────────────────────────────
# Step 1: compute recommended box from protein_oriented.gro
python3 box_match_helper.py

# Step 2: apply computed box dimensions
bash editconf_cmd.sh
"""
        (step_dir / "run.sh").write_text(run_sh)

        (step_dir / "metadata.json").write_text(json.dumps({
            "step_id":          step.step_id,
            "stage":            step.stage.value,
            "engine":           step.engine,
            "step_type":        "automatic",
            "automation_level": "automated",
            "lipid_type":       lipid_type,
            "fallback_used":    fallback,
            "lipid_params": {
                "bilayer_thickness_nm":  params.bilayer_thickness_nm,
                "apl_A2":                params.apl_A2,
                "lateral_padding_nm":    params.lateral_padding_nm,
                "solvent_z_padding_nm":  params.solvent_z_padding_nm,
                "protein_coverage_warn": params.protein_coverage_warn,
            },
            "expected_outputs": [
                "box_match_report.json",
                "box_match_report.md",
                "editconf_cmd.sh",
                "protein_boxed.gro",
            ],
            "gate": {
                "artifact": "box_match_report.json",
                "type":     "box_match_report",
            },
        }, indent=4))
