# builders/step_builders/membrane_orient_builder.py
"""
Builds the orient_protein step for membrane systems.

Consumes state.structural_annotation (via step.params["_orientation"]).
Generates:
    run.sh          — editconf -princ → orient_helper.py → rotate_cmd.sh
    orient_helper.py — standalone: reads GRO, computes rotation, writes rotate_cmd.sh

The helper respects extracellular_side (+z or -z) declared in
structural_annotation.orientation so the correct face ends up on the
requested axis after rotation, not just the GROMACS default +Z.
"""

from __future__ import annotations

from pathlib import Path
import json

from core.execution_models import SimulationStep


# Template tokens (replaced with str.replace so Python f-string braces survive):
#   {ec_set}         → repr(set of EC residue ints)
#   {ic_set}         → repr(set of IC residue ints)
#   {ec_target_side} → "+z" or "-z"
_ORIENT_HELPER_TEMPLATE = '''\
#!/usr/bin/env python3
"""
orient_helper.py — generated by SimForge membrane_orient_builder.
Reads protein_princ.gro, computes EC/IC Cα centres of mass, determines
the dominant TM axis, and writes rotate_cmd.sh with the correct angles.

EC_TARGET_SIDE controls which face of the Z axis the extracellular
residues end up on after rotation ("+z" is the GROMACS convention).
"""
import sys
from pathlib import Path

EC_RESIDUES    = {ec_set}
IC_RESIDUES    = {ic_set}
EC_TARGET_SIDE = "{ec_target_side}"   # "+z" or "-z"


def read_ca(gro_path, resids):
    """Return Cα positions (nm) for given residue numbers from a GRO file."""
    pts = []
    lines = Path(gro_path).read_text().splitlines()
    if len(lines) < 3:
        return pts
    n = int(lines[1].strip())
    for line in lines[2:2 + n]:
        if len(line) < 44:
            continue
        try:
            rnum = int(line[0:5])
            aname = line[10:15].strip()
        except ValueError:
            continue
        if rnum not in resids or aname != "CA":
            continue
        try:
            pts.append((float(line[20:28]), float(line[28:36]), float(line[36:44])))
        except ValueError:
            continue
    return pts


def mean_pos(pts):
    n = len(pts)
    return tuple(sum(p[i] for p in pts) / n for i in range(3))


gro = Path("protein_princ.gro")
if not gro.exists():
    sys.exit(f"ERROR: {gro} not found — run editconf -princ first.")

ec_pts = read_ca(gro, EC_RESIDUES)
ic_pts = read_ca(gro, IC_RESIDUES)

if not ec_pts:
    sys.exit("ERROR: No CA atoms found for EC residues. Check residue numbers.")
if not ic_pts:
    sys.exit("ERROR: No CA atoms found for IC residues. Check residue numbers.")

ec = mean_pos(ec_pts)
ic = mean_pos(ic_pts)
d = tuple(ec[i] - ic[i] for i in range(3))

axis  = max(range(3), key=lambda i: abs(d[i]))
delta = d[axis]

# Rotation angles to bring EC to +Z (standard GROMACS orientation).
# For each dominant axis, two cases depending on which side EC is on:
#   pos_rot → EC is at the positive end of the dominant axis (delta > 0)
#   neg_rot → EC is at the negative end of the dominant axis (delta < 0)
_ROTATIONS = {
    0: {"pos": (0.0, 270.0, 0.0), "neg": (0.0, 90.0, 0.0)},   # X axis
    1: {"pos": (-90.0, 0.0, 0.0), "neg": (90.0, 0.0, 0.0)},   # Y axis
    2: {"pos": (0.0, 0.0, 0.0),   "neg": (180.0, 0.0, 0.0)},  # Z axis
}

# If EC_TARGET_SIDE is "-z", swap pos/neg so EC ends on -Z instead.
want_plus_z = (EC_TARGET_SIDE == "+z")
side        = "pos" if (delta > 0) == want_plus_z else "neg"
rx, ry, rz  = _ROTATIONS[axis][side]

labels    = "XYZ"
direction = "+" if delta > 0 else "-"
print(f"EC COM       : {ec[0]:.3f}, {ec[1]:.3f}, {ec[2]:.3f} nm")
print(f"IC COM       : {ic[0]:.3f}, {ic[1]:.3f}, {ic[2]:.3f} nm")
print(f"TM axis      : {direction}{labels[axis]}  delta={delta:+.3f} nm")
print(f"Target EC side: {EC_TARGET_SIDE}")
print(f"Rotation     : rx={rx} ry={ry} rz={rz} degrees")

cmd = (
    f"gmx editconf -f protein_princ.gro -o protein_oriented.gro "
    f"-rotate {rx} {ry} {rz} -c -d 1.5 -bt triclinic\\n"
)
Path("rotate_cmd.sh").write_text(cmd)
print("Written: rotate_cmd.sh")
'''


# Standalone validation script embedded into the workspace (no SimForge imports).
# Tokens substituted by str.replace(): {ec_set}, {ic_set}, {tm_set}, {ec_target_side}
_VALIDATE_ORIENT_TEMPLATE = '''\
#!/usr/bin/env python3
"""
validate_orientation.py — generated by SimForge OrientationValidationLayer.
Reads protein_oriented.gro, validates EC/IC geometric coherence, and writes
orientation_report.json + orientation_report.md.

Exit code 1 when orientation is definitively inverted (EC on wrong Z side).
Warnings (small separation, tilt, TM off-center) do not trigger failure.
"""
import json
import math
import sys
from pathlib import Path

EC_RESIDUES    = {ec_set}
IC_RESIDUES    = {ic_set}
TM_RESIDUES    = {tm_set}
EC_TARGET_SIDE = "{ec_target_side}"

BILAYER_HALF_THICKNESS_NM = 2.0
MIN_EC_IC_SEPARATION_NM   = 0.5
MIN_EC_IC_DISTANCE_NM     = 1.0
MAX_TILT_ANGLE_DEG        = 45.0


def read_ca(gro_path, resids):
    pts = []
    if not resids:
        return pts
    lines = Path(gro_path).read_text().splitlines()
    if len(lines) < 3:
        return pts
    n = int(lines[1].strip())
    for line in lines[2:2 + n]:
        if len(line) < 44:
            continue
        try:
            rnum  = int(line[0:5])
            aname = line[10:15].strip()
        except ValueError:
            continue
        if rnum not in resids or aname != "CA":
            continue
        try:
            pts.append((float(line[20:28]), float(line[28:36]), float(line[36:44])))
        except ValueError:
            continue
    return pts


def mean_pos(pts):
    n = len(pts)
    return tuple(sum(p[i] for p in pts) / n for i in range(3))


gro = Path("protein_oriented.gro")
if not gro.exists():
    sys.exit(f"ERROR: {gro} not found — run orient_protein (steps 1-3) first.")

ec_pts = read_ca(gro, EC_RESIDUES)
ic_pts = read_ca(gro, IC_RESIDUES)
tm_pts = read_ca(gro, TM_RESIDUES)

checks   = []
warnings = []
errors   = []
penalty  = 0.0

ec_com = ic_com = None
ec_com_z = ic_com_z = tm_com_z = None
ec_ic_dist = tilt_deg = None

if not ec_pts:
    errors.append("No CA atoms found for EC residues — verify extracellular_regions residue numbers.")
    penalty += 0.35
if not ic_pts:
    errors.append("No CA atoms found for IC residues — verify intracellular_regions residue numbers.")
    penalty += 0.35

if ec_pts:
    ec_com   = mean_pos(ec_pts)
    ec_com_z = ec_com[2]
if ic_pts:
    ic_com   = mean_pos(ic_pts)
    ic_com_z = ic_com[2]
if tm_pts:
    tm_com_z = mean_pos(tm_pts)[2]

# ── Check 1: EC/IC on correct sides ──────────────────────────────────────────
if ec_com and ic_com:
    z_sep              = ec_com_z - ic_com_z
    ec_should_positive = (EC_TARGET_SIDE == "+z")
    ec_is_positive     = (z_sep > 0)
    abs_sep            = abs(z_sep)

    if ec_should_positive != ec_is_positive:
        msg = (f"Orientation inverted: EC COM_z={ec_com_z:+.3f} nm, "
               f"IC COM_z={ic_com_z:+.3f} nm — EC should be on {EC_TARGET_SIDE}. "
               "Check residue numbers or flip extracellular_side in the YAML.")
        errors.append(msg)
        penalty += 0.40
        checks.append({"name": "ec_ic_side", "passed": False, "message": msg,
                       "value": round(z_sep, 3), "threshold": 0.0})
    elif abs_sep < MIN_EC_IC_SEPARATION_NM:
        msg = f"EC/IC Z-separation small ({abs_sep:.3f} nm < {MIN_EC_IC_SEPARATION_NM} nm)."
        warnings.append(msg)
        penalty += 0.15
        checks.append({"name": "ec_ic_side", "passed": False, "message": msg,
                       "value": round(abs_sep, 3), "threshold": MIN_EC_IC_SEPARATION_NM})
    else:
        msg = f"EC/IC separation correct: EC={ec_com_z:+.3f} nm, IC={ic_com_z:+.3f} nm on {EC_TARGET_SIDE}."
        checks.append({"name": "ec_ic_side", "passed": True, "message": msg,
                       "value": round(abs_sep, 3), "threshold": MIN_EC_IC_SEPARATION_NM})

    # ── Check 2: EC→IC 3D distance ────────────────────────────────────────────
    d = tuple(ec_com[i] - ic_com[i] for i in range(3))
    ec_ic_dist = math.sqrt(sum(x**2 for x in d))
    if ec_ic_dist < MIN_EC_IC_DISTANCE_NM:
        msg = f"EC→IC vector short ({ec_ic_dist:.3f} nm < {MIN_EC_IC_DISTANCE_NM} nm)."
        warnings.append(msg)
        penalty += 0.15
        checks.append({"name": "ec_ic_distance", "passed": False, "message": msg,
                       "value": round(ec_ic_dist, 3), "threshold": MIN_EC_IC_DISTANCE_NM})
    else:
        msg = f"EC→IC distance sufficient ({ec_ic_dist:.3f} nm)."
        checks.append({"name": "ec_ic_distance", "passed": True, "message": msg,
                       "value": round(ec_ic_dist, 3), "threshold": MIN_EC_IC_DISTANCE_NM})

    # ── Check 3: Tilt angle ───────────────────────────────────────────────────
    if ec_ic_dist > 0:
        cos_t    = min(1.0, abs(d[2]) / ec_ic_dist)
        tilt_deg = math.degrees(math.acos(cos_t))
        if tilt_deg > MAX_TILT_ANGLE_DEG:
            msg = f"Tilt too large ({tilt_deg:.1f}° > {MAX_TILT_ANGLE_DEG}°)."
            warnings.append(msg)
            penalty += 0.15
            checks.append({"name": "tilt_angle", "passed": False, "message": msg,
                           "value": round(tilt_deg, 1), "threshold": MAX_TILT_ANGLE_DEG})
        else:
            msg = f"Tilt angle acceptable ({tilt_deg:.1f}° ≤ {MAX_TILT_ANGLE_DEG}°)."
            checks.append({"name": "tilt_angle", "passed": True, "message": msg,
                           "value": round(tilt_deg, 1), "threshold": MAX_TILT_ANGLE_DEG})

# ── Check 4: TM centered near Z=0 ────────────────────────────────────────────
if tm_pts:
    if abs(tm_com_z) > BILAYER_HALF_THICKNESS_NM:
        msg = (f"TM COM far from membrane plane (z={tm_com_z:+.3f} nm, "
               f"threshold ±{BILAYER_HALF_THICKNESS_NM} nm).")
        warnings.append(msg)
        penalty += 0.10
        checks.append({"name": "tm_centered", "passed": False, "message": msg,
                       "value": round(abs(tm_com_z), 3), "threshold": BILAYER_HALF_THICKNESS_NM})
    else:
        msg = f"TM COM near membrane plane (z={tm_com_z:+.3f} nm)."
        checks.append({"name": "tm_centered", "passed": True, "message": msg,
                       "value": round(abs(tm_com_z), 3), "threshold": BILAYER_HALF_THICKNESS_NM})

confidence = max(0.0, min(1.0, 1.0 - penalty))
passed     = len(errors) == 0

# ── Write orientation_report.json ────────────────────────────────────────────
def _r3(v): return round(v, 3) if v is not None else None
def _r1(v): return round(v, 1) if v is not None else None

report = {
    "confidence": round(confidence, 3),
    "passed":     passed,
    "geometry": {
        "ec_com_z_nm":       _r3(ec_com_z),
        "ic_com_z_nm":       _r3(ic_com_z),
        "tm_com_z_nm":       _r3(tm_com_z),
        "ec_ic_distance_nm": _r3(ec_ic_dist),
        "tilt_angle_deg":    _r1(tilt_deg),
        "n_ec_atoms": len(ec_pts),
        "n_ic_atoms": len(ic_pts),
        "n_tm_atoms": len(tm_pts),
    },
    "checks":   checks,
    "warnings": warnings,
    "errors":   errors,
}
Path("orientation_report.json").write_text(json.dumps(report, indent=4))

# ── Write orientation_report.md ───────────────────────────────────────────────
def _fz(v): return f"{v:+.3f} nm" if v is not None else "N/A"
def _fd(v): return f"{v:.3f} nm"  if v is not None else "N/A"
def _fa(v): return f"{v:.1f}°"    if v is not None else "N/A"

status = "PASS" if passed else "FAIL"
md_lines = [
    "# Orientation Validation Report",
    "",
    f"**Confidence:** {confidence:.2f}  **Status:** {status}",
    "",
    "## Geometry",
    "",
    "| Metric | Value |",
    "|---|---|",
    f"| EC COM (z) | {_fz(ec_com_z)} |",
    f"| IC COM (z) | {_fz(ic_com_z)} |",
    f"| TM COM (z) | {_fz(tm_com_z)} |",
    f"| EC→IC distance | {_fd(ec_ic_dist)} |",
    f"| Tilt angle (Z-axis) | {_fa(tilt_deg)} |",
    f"| EC atoms (Cα) | {len(ec_pts)} |",
    f"| IC atoms (Cα) | {len(ic_pts)} |",
    f"| TM atoms (Cα) | {len(tm_pts)} |",
    "",
    "## Checks",
    "",
]
for c in checks:
    icon = "✅" if c["passed"] else "❌"
    md_lines.append(f"{icon} {c['message']}")
md_lines += ["", "## Warnings", ""]
md_lines += [f"⚠️  {w}" for w in warnings] if warnings else ["_None_"]
md_lines += ["", "## Errors", ""]
md_lines += [f"❌  {e}" for e in errors] if errors else ["_None_"]
md_lines += ["", "---", "_Generated by SimForge OrientationValidationLayer_"]
Path("orientation_report.md").write_text("\\n".join(md_lines))

# ── Print summary ─────────────────────────────────────────────────────────────
print(f"Orientation confidence: {confidence:.2f}  [{status}]")
if errors:
    for e in errors:
        print(f"  ERROR: {e}")
if warnings:
    for w in warnings:
        print(f"  WARNING: {w}")
print("Written: orientation_report.json, orientation_report.md")

if errors:
    sys.exit(1)
'''


class MembraneOrientBuilder:
    """
    Builds the orient_protein step.

    If orientation data is present (EC/IC residues):
        → Automatic: generates run.sh + orient_helper.py + validate_orientation.py
    Otherwise:
        → Manual fallback: generates README.md only (no script)
    """

    def build(
        self,
        step:         SimulationStep,
        step_dir:     Path,
        step_dir_map: dict = {},
    ) -> None:
        orientation = step.params.get("_orientation")

        if orientation and (
            orientation.get("extracellular_residues")
            and orientation.get("intracellular_residues")
        ):
            self._build_automatic(step, step_dir, orientation)
        else:
            self._build_manual_readme(step, step_dir)

    # ── Automatic (EC/IC residues provided) ──────────────────────────────────

    def _build_automatic(
        self,
        step:        SimulationStep,
        step_dir:    Path,
        orientation: dict,
    ) -> None:
        from core.structural_annotation import residues_in_range

        ec_resids      = residues_in_range(orientation["extracellular_residues"])
        ic_resids      = residues_in_range(orientation["intracellular_residues"])
        tm_resids_raw  = orientation.get("tm_segments")
        tm_resids      = residues_in_range(tm_resids_raw) if tm_resids_raw else set()
        ec_target_side = orientation.get("extracellular_side", "+z")
        source_file    = step.params.get("source_file", "protein.pdb")

        # orient_helper.py — standalone, no SimForge imports at runtime.
        # str.replace() so Python f-string braces in the template survive.
        helper_code = (
            _ORIENT_HELPER_TEMPLATE
            .replace("{ec_set}", repr(ec_resids))
            .replace("{ic_set}", repr(ic_resids))
            .replace("{ec_target_side}", ec_target_side)
        )
        (step_dir / "orient_helper.py").write_text(helper_code)

        # validate_orientation.py — standalone validation script.
        validate_code = (
            _VALIDATE_ORIENT_TEMPLATE
            .replace("{ec_set}", repr(ec_resids))
            .replace("{ic_set}", repr(ic_resids))
            .replace("{tm_set}", repr(tm_resids))
            .replace("{ec_target_side}", ec_target_side)
        )
        (step_dir / "validate_orientation.py").write_text(validate_code)

        run_sh = f"""#!/bin/bash
# ─── orient_protein (automatic) ──────────────────────────────────────────────
# Step 1: align principal axes so TM axis is one of X/Y/Z
gmx editconf \\
    -f {source_file} \\
    -o protein_princ.gro \\
    -c -d 1.5 -bt triclinic -princ << 'EOF'
0
EOF

# Step 2: compute rotation from EC/IC Cα centres of mass
python3 orient_helper.py

# Step 3: apply computed rotation
bash rotate_cmd.sh

# Step 4: validate orientation geometry (writes orientation_report.json/.md)
python3 validate_orientation.py
"""
        (step_dir / "run.sh").write_text(run_sh)
        (step_dir / "metadata.json").write_text(json.dumps({
            "step_id":            step.step_id,
            "stage":              step.stage.value,
            "engine":             step.engine,
            "step_type":          "automatic",
            "automation_level":   "automated",
            "ec_residues":        orientation["extracellular_residues"],
            "ic_residues":        orientation["intracellular_residues"],
            "tm_residues":        tm_resids_raw,
            "extracellular_side": ec_target_side,
            "source_file":        source_file,
            "expected_outputs":   [
                "protein_oriented.gro",
                "orientation_report.json",
                "orientation_report.md",
            ],
            "gate": {
                "artifact": "orientation_report.json",
                "type":     "orientation_report",
            },
        }, indent=4))

    # ── Manual fallback (no orientation data) ────────────────────────────────

    def _build_manual_readme(
        self,
        step:     SimulationStep,
        step_dir: Path,
    ) -> None:
        note = step.params.get("note", "Ver documentación del pipeline.")
        notes_lines = "\n".join(f"- {n}" for n in step.notes) if step.notes else "- Sin notas"

        readme = f"""# {step.title}

## Acción requerida (manual)
No se proporcionaron residuos EC/IC en la configuración.
Inspecciona la estructura y determina la orientación manualmente.

## Instrucciones
```
{note}
```

## Para activar orientación automática
Usa el wizard interactivo:

    simforge annotate-structure <config.yaml>

O añade manualmente en tu YAML:

```yaml
structural_annotation:
  membrane_topology:
    extracellular_regions: ["1-50"]     # residuos en la cara extracelular
    intracellular_regions: ["200-250"]  # residuos en la cara intracelular
    transmembrane_segments: ["51-75"]   # opcional, informacional
  orientation:
    extracellular_side: "+z"            # "+z" (GROMACS estándar) o "-z"
    source: "user_annotation"
    confidence: 0.9
```

## Notas
{notes_lines}

## Cómo continuar
Crea `protein_oriented.gro` manualmente, luego:
    simforge run <workspace>
"""
        (step_dir / "README.md").write_text(readme)
        (step_dir / "metadata.json").write_text(json.dumps({
            "step_id":          step.step_id,
            "stage":            step.stage.value,
            "engine":           step.engine,
            "step_type":        "manual",
            "automation_level": "guided",
            "params":           step.params,
        }, indent=4))
