"""
tests/test_membrane_embedding_topology_bootstrap.py
────────────────────────────────────────────────────
Verify that:

1. dpp.itp exists in oplsaa_membrane.ff/ and has a valid [ moleculetype ] DPP.
2. After workspace build, dpp.itp is staged to membrane_assets/oplsaa_membrane.ff/.
3. The generated run_assemble_system.py includes dpp.itp instead of calling
   pdb2gmx on lipids_only.gro.
4. The generated run_assemble_system.py runs moleculetype validation in bootstrap
   mode and exits non-zero if DPP is in [ molecules ] without a moleculetype.
5. Bootstrap topology written by run_assemble_system.py includes dpp.itp.
6. LipidItpBuilder generates valid ITP content from RTP.
"""

import re
import json
import subprocess
import sys
from pathlib import Path
import pytest

_FF_DIR = Path(__file__).resolve().parent.parent / "docs" / "Prot-Memb_FILES" / "oplsaa_membrane.ff"


# ═══════════════════════════════════════════════════════════════════════════
# 1. Static dpp.itp asset
# ═══════════════════════════════════════════════════════════════════════════

class TestDppItpAsset:
    def test_dpp_itp_exists(self):
        assert (_FF_DIR / "dpp.itp").exists(), (
            "docs/Prot-Memb_FILES/oplsaa_membrane.ff/dpp.itp must exist "
            "(generated by core/lipid_itp_builder.py)"
        )

    def test_dpp_itp_has_moleculetype(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        assert re.search(r"^\[\s*moleculetype\s*\]", text, re.MULTILINE | re.IGNORECASE), (
            "dpp.itp must contain a [ moleculetype ] section"
        )

    def test_dpp_moleculetype_name(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        lines = text.splitlines()
        in_mt = False
        for line in lines:
            stripped = line.strip()
            if re.match(r"^\[\s*moleculetype\s*\]", stripped, re.IGNORECASE):
                in_mt = True
                continue
            if in_mt:
                if stripped and not stripped.startswith(";"):
                    name = stripped.split()[0]
                    assert name == "DPP", f"DPP moleculetype name should be 'DPP', got {name!r}"
                    return
        pytest.fail("No moleculetype name found in dpp.itp")

    def test_dpp_itp_has_atoms(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        assert re.search(r"^\[\s*atoms\s*\]", text, re.MULTILINE | re.IGNORECASE)
        atom_lines = [
            l for l in text.splitlines()
            if l.strip() and not l.strip().startswith(";") and not l.strip().startswith("[")
            and re.match(r"^\s*\d+", l)
        ]
        # Count only atom lines (6-column format)
        mt_passed = False
        atoms_passed = False
        in_atoms = False
        count = 0
        for line in text.splitlines():
            stripped = line.strip()
            if re.match(r"^\[\s*moleculetype\s*\]", stripped, re.IGNORECASE):
                mt_passed = True
            if re.match(r"^\[\s*atoms\s*\]", stripped, re.IGNORECASE) and mt_passed:
                in_atoms = True
                atoms_passed = True
                continue
            if in_atoms:
                if stripped.startswith("["):
                    break
                if stripped and not stripped.startswith(";"):
                    count += 1
        assert count == 50, f"DPP should have 50 atoms, found {count}"

    def test_dpp_itp_has_bonds(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        assert re.search(r"^\[\s*bonds\s*\]", text, re.MULTILINE | re.IGNORECASE)

    def test_dpp_itp_has_pairs(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        assert re.search(r"^\[\s*pairs\s*\]", text, re.MULTILINE | re.IGNORECASE)

    def test_dpp_itp_has_angles(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        assert re.search(r"^\[\s*angles\s*\]", text, re.MULTILINE | re.IGNORECASE)

    def test_dpp_itp_has_proper_dihedrals(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        # Should have at least one dihedrals section (proper)
        assert len(re.findall(r"^\[\s*dihedrals\s*\]", text, re.MULTILINE | re.IGNORECASE)) >= 2, (
            "dpp.itp must have at least 2 [ dihedrals ] sections "
            "(one proper func=3, one improper func=1)"
        )

    def test_dpp_zero_charge(self):
        text = (_FF_DIR / "dpp.itp").read_text()
        in_atoms = False
        mt_found = False
        charges = []
        for line in text.splitlines():
            stripped = line.strip()
            if re.match(r"^\[\s*moleculetype\s*\]", stripped, re.IGNORECASE):
                mt_found = True
            if re.match(r"^\[\s*atoms\s*\]", stripped, re.IGNORECASE) and mt_found:
                in_atoms = True
                continue
            if in_atoms:
                if stripped.startswith("["):
                    break
                if stripped and not stripped.startswith(";"):
                    parts = stripped.split()
                    if len(parts) >= 7:
                        try:
                            charges.append(float(parts[6]))
                        except ValueError:
                            pass
        total_charge = sum(charges)
        assert abs(total_charge) < 0.001, f"DPP total charge should be 0, got {total_charge:.6f}"

    def test_dpp_no_forcefield_include(self):
        """dpp.itp must NOT include forcefield.itp (it's already included by protein topology)."""
        text = (_FF_DIR / "dpp.itp").read_text()
        for line in text.splitlines():
            if "#include" in line and "forcefield" in line:
                pytest.fail(
                    f"dpp.itp must not include forcefield.itp — it will be included "
                    f"by the protein topology before dpp.itp is referenced. Line: {line!r}"
                )


# ═══════════════════════════════════════════════════════════════════════════
# 2. Workspace staging
# ═══════════════════════════════════════════════════════════════════════════

@pytest.fixture(scope="module")
def workspace(tmp_path_factory):
    """Build a membrane pipeline workspace; return the root path."""
    import os
    from core.compiler import SimulationCompiler
    from builders.workspace_builder import WorkspaceBuilder

    cfg_path = Path(__file__).resolve().parent.parent / "configs" / "membrane_orient_test.yaml"
    if not cfg_path.exists():
        pytest.skip(f"Test config not found: {cfg_path}")

    root = tmp_path_factory.mktemp("bootstrap_topology")
    orig_cwd = os.getcwd()
    os.chdir(cfg_path.parent)
    try:
        result = SimulationCompiler().compile(str(cfg_path))
    finally:
        os.chdir(orig_cwd)
    WorkspaceBuilder().build(result, workspace_path=root)
    return root


def _step_dir(workspace: Path, step_id: str) -> Path:
    matches = [d for d in (workspace / "steps").iterdir() if step_id in d.name]
    assert matches, f"Step '{step_id}' not found in {workspace / 'steps'}"
    return matches[0]


class TestDppItpStaging:
    def test_dpp_itp_staged_to_membrane_assets(self, workspace):
        staged = workspace / "membrane_assets" / "oplsaa_membrane.ff" / "dpp.itp"
        assert staged.exists(), (
            f"dpp.itp must be staged to membrane_assets/oplsaa_membrane.ff/ "
            f"but was not found at: {staged}"
        )

    def test_staged_dpp_itp_has_moleculetype(self, workspace):
        staged = workspace / "membrane_assets" / "oplsaa_membrane.ff" / "dpp.itp"
        text = staged.read_text()
        assert re.search(r"^\[\s*moleculetype\s*\]", text, re.MULTILINE | re.IGNORECASE)


# ═══════════════════════════════════════════════════════════════════════════
# 3. Generated script: no pdb2gmx on lipids; uses ITP include
# ═══════════════════════════════════════════════════════════════════════════

class TestAssembleScriptUsesItp:
    def test_no_pdb2gmx_on_lipids_only_gro(self, workspace):
        """run_assemble_system.py must NOT call pdb2gmx -f lipids_only.gro."""
        assemble_dir = _step_dir(workspace, "assemble_system_topology")
        script = (assemble_dir / "run_assemble_system.py").read_text()
        assert "lipids_only.gro" not in script or "pdb2gmx" not in script, (
            "run_assemble_system.py must not call pdb2gmx with lipids_only.gro"
        )
        # Stronger: if pdb2gmx appears, it must not be near lipids_only
        if "pdb2gmx" in script and "lipids_only.gro" in script:
            pdb2gmx_lines = [l for l in script.splitlines() if "pdb2gmx" in l or "lipids_only" in l]
            pytest.fail(
                "pdb2gmx and lipids_only.gro both appear in run_assemble_system.py:\n"
                + "\n".join(pdb2gmx_lines)
            )

    def test_script_has_lipid_itp_map(self, workspace):
        """run_assemble_system.py must contain _LIPID_ITP_MAP mapping DPP to dpp.itp."""
        assemble_dir = _step_dir(workspace, "assemble_system_topology")
        script = (assemble_dir / "run_assemble_system.py").read_text()
        assert "_LIPID_ITP_MAP" in script, (
            "run_assemble_system.py must define _LIPID_ITP_MAP for static ITP lookup"
        )
        assert "dpp.itp" in script, (
            "run_assemble_system.py must reference dpp.itp in _LIPID_ITP_MAP"
        )

    def test_script_references_itp_include(self, workspace):
        """run_assemble_system.py must build #include 'dpp.itp' rather than calling pdb2gmx."""
        assemble_dir = _step_dir(workspace, "assemble_system_topology")
        script = (assemble_dir / "run_assemble_system.py").read_text()
        assert "_lip_itp_path" in script or "_lip_itp_parts" in script, (
            "run_assemble_system.py must look up lipid ITP path from ASSETS_DIR"
        )

    def test_script_has_bootstrap_moltype_check(self, workspace):
        """run_assemble_system.py must run moleculetype validation before bootstrap sys.exit(0)."""
        assemble_dir = _step_dir(workspace, "assemble_system_topology")
        script = (assemble_dir / "run_assemble_system.py").read_text()
        assert "TOPOLOGY_ASSEMBLY_ERROR" in script or "Bootstrap moleculetype check" in script, (
            "run_assemble_system.py must validate moleculetypes in bootstrap mode "
            "(not silently skip the check)"
        )
        assert "_check_moltype_consistency" in script or "_collect_moleculetypes" in script, (
            "run_assemble_system.py must define a moleculetype consistency checker"
        )


# ═══════════════════════════════════════════════════════════════════════════
# 4. LipidItpBuilder generates correct content
# ═══════════════════════════════════════════════════════════════════════════

class TestLipidItpBuilder:
    def test_builder_produces_itp(self, tmp_path):
        from core.lipid_itp_builder import build_lipid_itp_from_rtp
        text = build_lipid_itp_from_rtp(_FF_DIR, "DPP")
        assert "[ moleculetype ]" in text
        assert "[ atoms ]" in text
        assert "[ bonds ]" in text
        assert "[ pairs ]" in text
        assert "[ angles ]" in text
        assert "[ dihedrals ]" in text
        assert "DPP" in text

    def test_builder_50_atoms(self):
        from core.lipid_itp_builder import build_lipid_itp_from_rtp
        text = build_lipid_itp_from_rtp(_FF_DIR, "DPP")
        in_atoms = False
        mt_found = False
        count = 0
        for line in text.splitlines():
            stripped = line.strip()
            if re.match(r"^\[\s*moleculetype\s*\]", stripped, re.IGNORECASE):
                mt_found = True
            if re.match(r"^\[\s*atoms\s*\]", stripped, re.IGNORECASE) and mt_found:
                in_atoms = True
                continue
            if in_atoms:
                if stripped.startswith("["):
                    break
                if stripped and not stripped.startswith(";"):
                    count += 1
        assert count == 50

    def test_builder_missing_residue_raises(self, tmp_path):
        from core.lipid_itp_builder import build_lipid_itp_from_rtp
        with pytest.raises(ValueError, match="not found"):
            build_lipid_itp_from_rtp(_FF_DIR, "NONEXISTENT_RESIDUE_XYZ")

    def test_builder_proper_dihedral_func_3(self):
        from core.lipid_itp_builder import build_lipid_itp_from_rtp
        text = build_lipid_itp_from_rtp(_FF_DIR, "DPP", proper_dih_func=3)
        # Find the [ dihedrals ] section that has the "proper dihedrals" comment after it
        # (not the improper section). Check that dihedral entries use func=3.
        lines = text.splitlines()
        found_func3 = False
        i = 0
        while i < len(lines):
            stripped = lines[i].strip()
            if re.match(r"^\[\s*dihedrals\s*\]", stripped, re.IGNORECASE):
                # Peek at next non-empty, non-bracket line to determine section type
                j = i + 1
                while j < len(lines) and (not lines[j].strip() or lines[j].strip().startswith(";")):
                    comment = lines[j].strip().lower()
                    if "proper" in comment and "improper" not in comment:
                        # This is the proper dihedrals section — scan entries
                        k = j + 1
                        while k < len(lines):
                            entry = lines[k].strip()
                            if entry.startswith("["):
                                break
                            if entry and not entry.startswith(";"):
                                parts = entry.split()
                                if len(parts) >= 5 and parts[4] == "3":
                                    found_func3 = True
                                break
                            k += 1
                        break
                    if lines[j].strip().startswith("["):
                        break
                    j += 1
            i += 1
        assert found_func3, "DPP ITP must have proper dihedrals with func=3 (Ryckaert-Bellemans)"

    def test_lipid_itp_registry_has_dpp(self):
        from core.lipid_itp_builder import LIPID_ITP_REGISTRY
        assert "DPP" in LIPID_ITP_REGISTRY
        assert LIPID_ITP_REGISTRY["DPP"] == "dpp.itp"


# ═══════════════════════════════════════════════════════════════════════════
# 5. Bootstrap mode execution: script exits 1 on missing moleculetype
# ═══════════════════════════════════════════════════════════════════════════

class TestBootstrapMoltypeValidation:
    """Test the moleculetype consistency checker embedded in run_assemble_system.py."""

    def test_bootstrap_script_contains_error_message(self, workspace):
        """run_assemble_system.py must contain TOPOLOGY_ASSEMBLY_ERROR string."""
        assemble_dir = _step_dir(workspace, "assemble_system_topology")
        script = (assemble_dir / "run_assemble_system.py").read_text()
        assert "TOPOLOGY_ASSEMBLY_ERROR" in script, (
            "run_assemble_system.py must emit TOPOLOGY_ASSEMBLY_ERROR when a moleculetype "
            "is in [ molecules ] but not defined (caught before grompp runs)"
        )

    def test_moltype_checker_inline(self, tmp_path):
        """The _collect_moleculetypes logic catches undefined moleculetypes."""
        # Write a minimal topology with DPP in [ molecules ] but no definition
        top = tmp_path / "broken.top"
        top.write_text(
            "; no moleculetype definitions here\n"
            "\n"
            "[ system ]\nTest\n\n"
            "[ molecules ]\n"
            "DPP  100\n"
        )
        # Inline the same logic as in the generated script
        check_script = tmp_path / "check.py"
        check_script.write_text(
            "import re, sys\n"
            "from pathlib import Path\n"
            "\n"
            "def _collect_moleculetypes(f, visited=None):\n"
            "    if visited is None: visited = set()\n"
            "    key = str(Path(f).resolve())\n"
            "    if key in visited: return []\n"
            "    visited.add(key)\n"
            "    result = []\n"
            "    try: txt = Path(f).read_text()\n"
            "    except OSError: return result\n"
            "    _in_mt = False\n"
            "    for _l in txt.splitlines():\n"
            "        _ls = _l.lstrip()\n"
            "        if re.match(r'^\\[\\s*moleculetype\\s*\\]', _ls, re.IGNORECASE):\n"
            "            _in_mt = True; continue\n"
            "        if _in_mt:\n"
            "            if _ls and not _ls.startswith(';') and not _ls.startswith('['):\n"
            "                result.append(_ls.split()[0]); _in_mt = False\n"
            "            elif _ls.startswith('['):\n"
            "                _in_mt = False\n"
            "        if _ls.startswith('#include'):\n"
            "            _pts = _ls.split('\"')\n"
            "            if len(_pts) >= 2:\n"
            "                _cand = (Path(f).parent / _pts[1]).resolve()\n"
            "                if _cand.exists(): result += _collect_moleculetypes(str(_cand), visited)\n"
            "    return result\n"
            "\n"
            "top = Path(sys.argv[1])\n"
            "defined = set(_collect_moleculetypes(str(top)))\n"
            "txt = top.read_text()\n"
            "mol_m = re.search(r'^\\s*\\[\\s*molecules\\s*\\](.*)', txt,\n"
            "                  re.MULTILINE | re.IGNORECASE | re.DOTALL)\n"
            "mol_names = []\n"
            "if mol_m:\n"
            "    for mbl in mol_m.group(1).splitlines():\n"
            "        mbl = mbl.strip()\n"
            "        if mbl and not mbl.startswith(';') and not mbl.startswith('#'):\n"
            "            mbs = mbl.split()\n"
            "            if mbs: mol_names.append(mbs[0])\n"
            "undef = [n for n in mol_names if n not in defined]\n"
            "for u in undef:\n"
            "    print(f'TOPOLOGY_ASSEMBLY_ERROR: {u!r} undefined', file=sys.stderr)\n"
            "sys.exit(1 if undef else 0)\n"
        )

        ret = subprocess.run(
            [sys.executable, str(check_script), str(top)],
            capture_output=True,
            text=True,
        )
        assert ret.returncode == 1, "Check must exit 1 for missing moleculetype DPP"
        assert "DPP" in ret.stderr and "TOPOLOGY_ASSEMBLY_ERROR" in ret.stderr

    def test_moltype_checker_passes_with_valid_top(self, tmp_path):
        """Checker exits 0 when all moleculetypes in [ molecules ] are defined."""
        dpp_itp = tmp_path / "dpp.itp"
        dpp_itp.write_text(
            "[ moleculetype ]\nDPP  3\n\n"
            "[ atoms ]\n; (empty for test)\n"
        )
        top = tmp_path / "valid.top"
        top.write_text(
            f'#include "dpp.itp"\n\n'
            "[ system ]\nTest\n\n"
            "[ molecules ]\n"
            "DPP  100\n"
        )
        check_script = tmp_path / "check.py"
        check_script.write_text(
            "import re, sys\n"
            "from pathlib import Path\n"
            "\n"
            "def _collect_moleculetypes(f, visited=None):\n"
            "    if visited is None: visited = set()\n"
            "    key = str(Path(f).resolve())\n"
            "    if key in visited: return []\n"
            "    visited.add(key)\n"
            "    result = []\n"
            "    try: txt = Path(f).read_text()\n"
            "    except OSError: return result\n"
            "    _in_mt = False\n"
            "    for _l in txt.splitlines():\n"
            "        _ls = _l.lstrip()\n"
            "        if re.match(r'^\\[\\s*moleculetype\\s*\\]', _ls, re.IGNORECASE):\n"
            "            _in_mt = True; continue\n"
            "        if _in_mt:\n"
            "            if _ls and not _ls.startswith(';') and not _ls.startswith('['):\n"
            "                result.append(_ls.split()[0]); _in_mt = False\n"
            "            elif _ls.startswith('['):\n"
            "                _in_mt = False\n"
            "        if _ls.startswith('#include'):\n"
            "            _pts = _ls.split('\"')\n"
            "            if len(_pts) >= 2:\n"
            "                _cand = (Path(f).parent / _pts[1]).resolve()\n"
            "                if _cand.exists(): result += _collect_moleculetypes(str(_cand), visited)\n"
            "    return result\n"
            "\n"
            "top = Path(sys.argv[1])\n"
            "defined = set(_collect_moleculetypes(str(top)))\n"
            "txt = top.read_text()\n"
            "mol_m = re.search(r'^\\s*\\[\\s*molecules\\s*\\](.*)', txt,\n"
            "                  re.MULTILINE | re.IGNORECASE | re.DOTALL)\n"
            "mol_names = []\n"
            "if mol_m:\n"
            "    for mbl in mol_m.group(1).splitlines():\n"
            "        mbl = mbl.strip()\n"
            "        if mbl and not mbl.startswith(';') and not mbl.startswith('#'):\n"
            "            mbs = mbl.split()\n"
            "            if mbs: mol_names.append(mbs[0])\n"
            "undef = [n for n in mol_names if n not in defined]\n"
            "sys.exit(1 if undef else 0)\n"
        )

        ret = subprocess.run(
            [sys.executable, str(check_script), str(top)],
            capture_output=True,
            text=True,
        )
        assert ret.returncode == 0, (
            f"Check must exit 0 when DPP moleculetype is defined. stderr: {ret.stderr!r}"
        )
