"""
runtime/test_membrane_gates.py — tests for the 4 new membrane gates.

Each gate reads a JSON report file written by the corresponding run script.
Gates never raise; they return None when the report is absent.
"""
import json
import pytest
from pathlib import Path

from runtime.overlap_gate   import evaluate_overlap_gate
from runtime.topology_gate  import evaluate_topology_gate
from runtime.apl_gate       import evaluate_apl_gate
from runtime.water_gate     import evaluate_water_gate
from runtime.gate_runner    import run_gate, GATE_LABELS, GateResult


# ─── helpers ──────────────────────────────────────────────────────────────────

def _w(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data))


# ══════════════════════════════════════════════════════════════════════════════
# overlap_gate
# ══════════════════════════════════════════════════════════════════════════════

class TestOverlapGate:

    def test_missing_report_returns_none(self, tmp_path):
        assert evaluate_overlap_gate(tmp_path) is None

    def test_corrupted_json_returns_none(self, tmp_path):
        (tmp_path / "overlap_report.json").write_text("not json")
        assert evaluate_overlap_gate(tmp_path) is None

    def test_clean_pass(self, tmp_path):
        _w(tmp_path / "overlap_report.json", {
            "passed": True, "n_clashes": 0, "n_protein_atoms": 500,
            "n_lipid_atoms": 8000, "errors": [], "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_overlap_gate(tmp_path)
        assert gate is not None
        assert gate.passed is True
        assert gate.blocked is False
        assert gate.errors == []

    def test_clashes_block(self, tmp_path):
        _w(tmp_path / "overlap_report.json", {
            "passed": False, "n_clashes": 42,
            "errors": ["42 clash(es) detected between protein and DPPC atoms"],
            "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_overlap_gate(tmp_path)
        assert gate.blocked is True
        assert len(gate.errors) == 1
        assert "42" in gate.errors[0]

    def test_warnings_not_blocked(self, tmp_path):
        _w(tmp_path / "overlap_report.json", {
            "passed": True, "n_clashes": 0,
            "errors": [], "warnings": ["Protein footprint covers 70% of box XY"], "confidence": 0.9,
        })
        gate = evaluate_overlap_gate(tmp_path)
        assert gate.blocked is False
        assert gate.warnings != []

    def test_confidence_propagated(self, tmp_path):
        _w(tmp_path / "overlap_report.json", {
            "passed": True, "errors": [], "warnings": [], "confidence": 0.75,
        })
        gate = evaluate_overlap_gate(tmp_path)
        assert gate.confidence == 0.75


# ══════════════════════════════════════════════════════════════════════════════
# topology_gate
# ══════════════════════════════════════════════════════════════════════════════

class TestTopologyGate:

    def test_missing_report_returns_none(self, tmp_path):
        assert evaluate_topology_gate(tmp_path) is None

    def test_corrupted_json_returns_none(self, tmp_path):
        (tmp_path / "topology_consistency_report.json").write_text("{bad")
        assert evaluate_topology_gate(tmp_path) is None

    def test_clean_pass(self, tmp_path):
        _w(tmp_path / "topology_consistency_report.json", {
            "passed": True, "top_exists": True, "posre_included": True,
            "strong_posre_included": True, "errors": [], "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_topology_gate(tmp_path)
        assert gate.passed is True
        assert gate.blocked is False

    def test_missing_topology_blocks(self, tmp_path):
        _w(tmp_path / "topology_consistency_report.json", {
            "passed": False, "top_exists": False,
            "errors": ["topol.top not generated by pdb2gmx"], "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_topology_gate(tmp_path)
        assert gate.blocked is True
        assert "topol.top" in gate.errors[0]

    def test_missing_posre_blocks(self, tmp_path):
        _w(tmp_path / "topology_consistency_report.json", {
            "passed": False, "top_exists": True, "posre_included": False,
            "errors": ["posre.itp not referenced in topol.top — pdb2gmx may have failed silently"],
            "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_topology_gate(tmp_path)
        assert gate.blocked is True
        assert any("posre.itp" in e for e in gate.errors)

    def test_missing_strong_posre_is_warning(self, tmp_path):
        _w(tmp_path / "topology_consistency_report.json", {
            "passed": True, "top_exists": True, "posre_included": True,
            "strong_posre_included": False,
            "errors": [],
            "warnings": ["strong_posre.itp not injected into topol.top"],
            "confidence": 1.0,
        })
        gate = evaluate_topology_gate(tmp_path)
        assert gate.blocked is False
        assert any("strong_posre" in w for w in gate.warnings)


# ══════════════════════════════════════════════════════════════════════════════
# apl_gate
# ══════════════════════════════════════════════════════════════════════════════

class TestAplGate:

    def test_missing_telemetry_returns_none(self, tmp_path):
        assert evaluate_apl_gate(tmp_path) is None

    def test_corrupted_json_returns_none(self, tmp_path):
        (tmp_path / "shrink_telemetry.json").write_text("bad")
        assert evaluate_apl_gate(tmp_path) is None

    def test_converged_pass(self, tmp_path):
        _w(tmp_path / "shrink_telemetry.json", {
            "converged": True, "final_apl_ang2": 62, "n_iterations": 45,
        })
        gate = evaluate_apl_gate(tmp_path)
        assert gate.passed is True
        assert gate.blocked is False

    def test_not_converged_blocks(self, tmp_path):
        _w(tmp_path / "shrink_telemetry.json", {
            "converged": False, "final_apl_ang2": 75, "n_iterations": 200,
        })
        gate = evaluate_apl_gate(tmp_path)
        assert gate.blocked is True
        assert gate.errors != []

    def test_near_tolerance_warns(self, tmp_path):
        # APL = 65.4 vs target=64 + tol=2.0 → cutoff=66.0; gap=0.6 < 0.5 (25% of 2.0)
        _w(tmp_path / "shrink_telemetry.json", {
            "converged": True, "final_apl_ang2": 65.6, "n_iterations": 99,
        })
        _w(tmp_path / "metadata.json", {
            "params": {"apl_target_ang2": 64.0, "apl_tolerance_ang2": 2.0},
        })
        gate = evaluate_apl_gate(tmp_path)
        assert gate.blocked is False
        assert gate.warnings != []

    def test_comfortably_converged_no_warning(self, tmp_path):
        _w(tmp_path / "shrink_telemetry.json", {
            "converged": True, "final_apl_ang2": 60.0, "n_iterations": 30,
        })
        _w(tmp_path / "metadata.json", {
            "params": {"apl_target_ang2": 64.0, "apl_tolerance_ang2": 2.0},
        })
        gate = evaluate_apl_gate(tmp_path)
        assert gate.blocked is False
        assert gate.warnings == []

    def test_no_metadata_still_passes(self, tmp_path):
        _w(tmp_path / "shrink_telemetry.json", {
            "converged": True, "final_apl_ang2": 62, "n_iterations": 40,
        })
        gate = evaluate_apl_gate(tmp_path)
        assert gate.passed is True


# ══════════════════════════════════════════════════════════════════════════════
# water_gate
# ══════════════════════════════════════════════════════════════════════════════

class TestWaterGate:

    def test_missing_report_returns_none(self, tmp_path):
        assert evaluate_water_gate(tmp_path) is None

    def test_corrupted_json_returns_none(self, tmp_path):
        (tmp_path / "water_report.json").write_text("broken")
        assert evaluate_water_gate(tmp_path) is None

    def test_no_waters_remaining_pass(self, tmp_path):
        _w(tmp_path / "water_report.json", {
            "passed": True, "waters_removed": 247, "n_waters_remaining": 0,
            "errors": [], "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.passed is True
        assert gate.blocked is False

    def test_many_waters_remaining_blocks(self, tmp_path):
        # >5 waters: script writes errors list → gate blocks
        n_remain = 20
        msg = f"{n_remain} water oxygen(s) inside bilayer core"
        _w(tmp_path / "water_report.json", {
            "passed": False, "waters_removed": 100, "n_waters_remaining": n_remain,
            "errors": [msg], "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.blocked is True
        assert gate.errors != []

    def test_few_waters_remaining_warns_not_blocks(self, tmp_path):
        # 1–5 waters: script writes warnings list → gate advises but does not block
        n_remain = 3
        msg = f"{n_remain} water oxygen(s) inside bilayer core"
        _w(tmp_path / "water_report.json", {
            "passed": False, "waters_removed": 245, "n_waters_remaining": n_remain,
            "errors": [], "warnings": [msg], "confidence": 1.0,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.blocked is False
        assert gate.warnings != []

    def test_exactly_five_waters_warns_not_blocks(self, tmp_path):
        # boundary: exactly 5 → warning (not blocked)
        msg = "5 water oxygen(s) inside bilayer core"
        _w(tmp_path / "water_report.json", {
            "passed": False, "n_waters_remaining": 5,
            "errors": [], "warnings": [msg], "confidence": 1.0,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.blocked is False
        assert gate.warnings != []

    def test_six_waters_blocks(self, tmp_path):
        # boundary: 6 → error (blocked)
        msg = "6 water oxygen(s) inside bilayer core"
        _w(tmp_path / "water_report.json", {
            "passed": False, "n_waters_remaining": 6,
            "errors": [msg], "warnings": [], "confidence": 1.0,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.blocked is True

    def test_explicit_errors_in_report_override(self, tmp_path):
        _w(tmp_path / "water_report.json", {
            "passed": False,
            "errors": ["WaterDeletorAdapter returned no headgroup atoms"],
            "warnings": [], "confidence": 0.5,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.blocked is True

    def test_waters_removed_zero_no_block(self, tmp_path):
        _w(tmp_path / "water_report.json", {
            "passed": True, "waters_removed": 0, "n_waters_remaining": 0,
            "errors": [], "warnings": ["No headgroup atoms found — bilayer may not be present"],
            "confidence": 0.6,
        })
        gate = evaluate_water_gate(tmp_path)
        assert gate.blocked is False


# ══════════════════════════════════════════════════════════════════════════════
# gate_runner dispatcher
# ══════════════════════════════════════════════════════════════════════════════

class TestGateRunner:

    def test_unknown_type_returns_none(self, tmp_path):
        assert run_gate("nonexistent_gate", tmp_path) is None

    def test_overlap_dispatched(self, tmp_path):
        _w(tmp_path / "overlap_report.json", {
            "passed": True, "n_clashes": 0, "errors": [], "warnings": [], "confidence": 1.0,
        })
        result = run_gate("overlap_report", tmp_path)
        assert isinstance(result, GateResult)
        assert result.passed is True

    def test_topology_dispatched(self, tmp_path):
        _w(tmp_path / "topology_consistency_report.json", {
            "passed": True, "top_exists": True, "errors": [], "warnings": [], "confidence": 1.0,
        })
        result = run_gate("topology_consistency", tmp_path)
        assert isinstance(result, GateResult)

    def test_apl_dispatched(self, tmp_path):
        _w(tmp_path / "shrink_telemetry.json", {
            "converged": True, "final_apl_ang2": 62, "n_iterations": 30,
        })
        result = run_gate("apl_report", tmp_path)
        assert isinstance(result, GateResult)
        assert result.blocked is False

    def test_water_dispatched(self, tmp_path):
        _w(tmp_path / "water_report.json", {
            "passed": True, "n_waters_remaining": 0, "errors": [], "warnings": [], "confidence": 1.0,
        })
        result = run_gate("water_report", tmp_path)
        assert isinstance(result, GateResult)

    def test_legacy_orientation_wrapped_to_gate_result(self, tmp_path):
        (tmp_path / "orientation_report.json").write_text(json.dumps({
            "passed": True, "confidence": 0.9, "errors": [], "warnings": [],
        }))
        result = run_gate("orientation_report", tmp_path)
        assert isinstance(result, GateResult)
        assert result.passed is True

    def test_legacy_box_match_wrapped_to_gate_result(self, tmp_path):
        (tmp_path / "box_match_report.json").write_text(json.dumps({
            "passed": True, "confidence": 0.95, "errors": [], "warnings": [],
        }))
        result = run_gate("box_match_report", tmp_path)
        assert isinstance(result, GateResult)

    def test_all_gate_types_have_labels(self):
        for gt in ("orientation_report", "box_match_report", "overlap_report",
                   "topology_consistency", "apl_report", "water_report"):
            assert gt in GATE_LABELS
            assert len(GATE_LABELS[gt]) > 0
