"""Unit tests for utils/itp_parser.py."""

import textwrap
from pathlib import Path

import pytest

from utils.itp_parser import ItpFile, MoleculetypeRecord, AtomRecord, parse_itp


# ── sample ITP content ────────────────────────────────────────────────────────

SAMPLE_ITP = textwrap.dedent("""\
    ; Generated by LigParGen
    ; Molecule: LIG

    [ moleculetype ]
    ; Name    nrexcl
    LIG         3

    [ atoms ]
    ;   nr  type  resi  res   atom  cgnr   charge    mass
         1  C135     1  LIG    C1     1   -0.1800  12.0110
         2  C135     1  LIG    C2     2   -0.1800  12.0110
         3   H46     1  LIG    H1     3    0.0600   1.0080
         4   H46     1  LIG    H2     4    0.0600   1.0080

    [ bonds ]
    1 2 1
    2 3 1
""")

MINIMAL_ITP = textwrap.dedent("""\
    [ moleculetype ]
    MOL 3

    [ atoms ]
    1 CT 1 MOL CA 1 0.5000 12.011
    2 CT 1 MOL CB 2 -0.5000 12.011
""")

COMMENTS_ONLY_ITP = textwrap.dedent("""\
    ; just comments
    ; nothing else
""")


@pytest.fixture
def sample_itp(tmp_path: Path) -> Path:
    p = tmp_path / "lig.itp"
    p.write_text(SAMPLE_ITP)
    return p


@pytest.fixture
def minimal_itp(tmp_path: Path) -> Path:
    p = tmp_path / "mol.itp"
    p.write_text(MINIMAL_ITP)
    return p


# ── moleculetype ──────────────────────────────────────────────────────────────

def test_moleculetype_name(sample_itp):
    itp = parse_itp(sample_itp)
    assert itp.moleculetype is not None
    assert itp.moleculetype.name == "LIG"


def test_moleculetype_nrexcl(sample_itp):
    itp = parse_itp(sample_itp)
    assert itp.moleculetype.nrexcl == 3


def test_moleculetype_minimal(minimal_itp):
    itp = parse_itp(minimal_itp)
    assert itp.moleculetype.name == "MOL"


# ── atoms ─────────────────────────────────────────────────────────────────────

def test_atom_count(sample_itp):
    itp = parse_itp(sample_itp)
    assert len(itp.atoms) == 4


def test_atom_names(sample_itp):
    itp = parse_itp(sample_itp)
    names = [a.atom_name for a in itp.atoms]
    assert names == ["C1", "C2", "H1", "H2"]


def test_atom_types(sample_itp):
    itp = parse_itp(sample_itp)
    types = [a.atom_type for a in itp.atoms]
    assert types == ["C135", "C135", "H46", "H46"]


def test_atom_charges(sample_itp):
    itp = parse_itp(sample_itp)
    charges = [a.charge for a in itp.atoms]
    assert charges == pytest.approx([-0.18, -0.18, 0.06, 0.06], abs=1e-6)


def test_atom_mass(sample_itp):
    itp = parse_itp(sample_itp)
    assert itp.atoms[0].mass == pytest.approx(12.011, abs=1e-4)


def test_atom_residue_name(sample_itp):
    itp = parse_itp(sample_itp)
    assert all(a.residue_name == "LIG" for a in itp.atoms)


# ── total charge ──────────────────────────────────────────────────────────────

def test_total_charge_near_zero(sample_itp):
    itp = parse_itp(sample_itp)
    # -0.18 -0.18 +0.06 +0.06 = -0.24
    assert itp.total_charge == pytest.approx(-0.24, abs=1e-6)


def test_total_charge_zero(minimal_itp):
    itp = parse_itp(minimal_itp)
    assert itp.total_charge == pytest.approx(0.0, abs=1e-9)


def test_charge_is_integer_true(minimal_itp):
    itp = parse_itp(minimal_itp)
    assert itp.charge_is_integer() is True


def test_charge_is_integer_false(sample_itp):
    itp = parse_itp(sample_itp)
    assert itp.charge_is_integer() is False


# ── sections ──────────────────────────────────────────────────────────────────

def test_sections_keys(sample_itp):
    itp = parse_itp(sample_itp)
    assert "moleculetype" in itp.sections
    assert "atoms" in itp.sections
    assert "bonds" in itp.sections


def test_bonds_section_parsed(sample_itp):
    itp = parse_itp(sample_itp)
    assert len(itp.sections["bonds"]) >= 1


# ── comments and blank lines ──────────────────────────────────────────────────

def test_comments_only(tmp_path):
    p = tmp_path / "empty.itp"
    p.write_text(COMMENTS_ONLY_ITP)
    itp = parse_itp(p)
    assert itp.moleculetype is None
    assert itp.atoms == []


def test_inline_comment_stripped(tmp_path):
    p = tmp_path / "inline.itp"
    p.write_text(
        "[ moleculetype ]\n"
        "MYLIG 3 ; this is a comment\n"
        "[ atoms ]\n"
    )
    itp = parse_itp(p)
    assert itp.moleculetype.name == "MYLIG"


# ── no mass field ─────────────────────────────────────────────────────────────

def test_atom_no_mass(tmp_path):
    p = tmp_path / "nomass.itp"
    p.write_text(
        "[ moleculetype ]\nLIG 3\n"
        "[ atoms ]\n"
        "1 CT 1 LIG CA 1 0.2500\n"
    )
    itp = parse_itp(p)
    assert itp.atoms[0].mass is None
    assert itp.atoms[0].charge == pytest.approx(0.25)
