"""
Unit tests for ligand/integrate.py and ligand/prepare.py.

All tests are pure Python — no GROMACS or RDKit required.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from unittest.mock import MagicMock, patch

import pytest
import yaml

from ligand.integrate import (
    AssemblyResult,
    Pdb2gmxMeta,
    _should_retry_with_ignh,
    extract_atomtypes_section,
    generate_topol_top,
    merge_gro_files,
    remove_atomtypes_from_itp,
    run_pdb2gmx,
    split_topol_top,
    validate_system,
)
from ligand.prepare import (
    _has_hydrogens,
    _count_heavy_atoms,
    _count_h_atoms,
    _determine_hydrogenation_status,
    detect_ligand_residues,
    extract_ligand_from_complex,
)
from utils.gro_parser import GroAtom, GroFile, parse_gro, write_gro


# ═══════════════════════════════════════════════════════════════════════════════
# Shared fixtures
# ═══════════════════════════════════════════════════════════════════════════════

_MINIMAL_PROTEIN_GRO = dedent("""\
    Protein in water
       5
        1ALA      N    1   1.000   1.000   1.000
        1ALA     CA    2   1.100   1.000   1.000
        1ALA      C    3   1.200   1.000   1.000
        1ALA      O    4   1.250   1.050   1.000
        1ALA     CB    5   1.100   1.100   1.000
       5.00000   5.00000   5.00000
""")

_MINIMAL_LIGAND_GRO = dedent("""\
    LIGPARGEN GENERATED GRO FILE
       3
        1E20     C1    1   3.000   3.000   3.000
        1E20     O1    2   3.100   3.000   3.000
        1E20     H1    3   3.150   3.050   3.000
       5.00000   5.00000   5.00000
""")

_LIGAND_ITP_WITH_ATOMTYPES = dedent("""\
    ;
    ; GENERATED BY LigParGen Server
    ;
    [ atomtypes ]
      opls_100  C100    12.0110     0.000    A    3.50000E-01   2.76144E-01
      opls_101  O101    15.9990     0.000    A    2.90000E-01   5.85760E-01
      opls_102  H102     1.0080     0.000    A    2.50000E-01   1.25520E-01
    [ moleculetype ]
    ; Name               nrexcl
    E20                 3
    [ atoms ]
    ;   nr       type  resnr residue  atom   cgnr     charge       mass
         1   opls_100      1    E20    C1      1     0.1000    12.0110
         2   opls_101      1    E20    O1      1    -0.2000    15.9990
         3   opls_102      1    E20    H1      1     0.1000     1.0080
    [ bonds ]
    ; ai   aj  funct   c0         c1
       1    2    1   1.23000e-01   3.62000e+05
       2    3    1   9.60000e-02   4.63000e+05
""")

_MINIMAL_TOPOL_TOP = dedent("""\
    ;
    ; File topol.top was generated by gmx pdb2gmx
    ;
    ; Include forcefield parameters
    #include "oplsaa.ff/forcefield.itp"

    [ moleculetype ]
    ; Name            nrexcl
    Protein_chain_A     3

    [ atoms ]
    ;   nr       type  resnr residue  atom   cgnr     charge       mass
         1 opls_238     1 ALA    N      1    -0.3    14.007
         2 opls_224     1 ALA   CA      1     0.1    12.011
         3 opls_235     1 ALA    C      1     0.5    12.011
         4 opls_236     1 ALA    O      1    -0.5    15.999
         5 opls_135     1 ALA   CB      1    -0.1    12.011

    [ bonds ]
       1    2    1
       2    3    1
       3    4    2
       2    5    1

    ; Include Position restraint file
    #ifdef POSRES
    #include "posre.itp"
    #endif

    ; Include water topology
    #include "oplsaa.ff/spce.itp"

    #ifdef POSRES_WATER
    ; Position restraint for each water molecule
    [ position_restraints ]
    ; i funct       fcx        fcy        fcz
      1    1       1000       1000       1000
    #endif

    ; Include topology for ions
    #include "oplsaa.ff/ions.itp"

    [ system ]
    ; Name
    Protein in water

    [ molecules ]
    ; Compound        #mols
    Protein_chain_A     1
""")

_MINIMAL_DOCKED_COMPLEX_PDB = dedent("""\
    ATOM      1  N   ALA A   1       7.500   7.500   7.500  1.00  0.00           N
    ATOM      2  CA  ALA A   1       8.100   7.500   7.500  1.00  0.00           C
    ATOM      3  C   ALA A   1       8.700   7.500   7.500  1.00  0.00           C
    HETATM    4  C1  E20 A 201      15.000  15.000  15.000  1.00  0.00           C
    HETATM    5  O1  E20 A 201      15.600  15.000  15.000  1.00  0.00           O
    HETATM    6  H1  E20 A 201      15.900  15.300  15.000  1.00  0.00           H
    CONECT    4    5
    CONECT    5    6
    END
""")


# ═══════════════════════════════════════════════════════════════════════════════
# extract_atomtypes_section
# ═══════════════════════════════════════════════════════════════════════════════

class TestExtractAtomtypesSection:
    def test_extracts_block_correctly(self):
        block, remaining = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        assert "[ atomtypes ]" in block
        assert "opls_100" in block
        assert "opls_101" in block

    def test_remaining_has_no_atomtypes_section(self):
        _, remaining = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        assert "[ atomtypes ]" not in remaining
        # Note: atom type names (opls_XXX) still appear in [ atoms ] — that is correct.

    def test_remaining_preserves_moleculetype(self):
        _, remaining = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        assert "[ moleculetype ]" in remaining
        assert "E20" in remaining

    def test_remaining_preserves_bonds(self):
        _, remaining = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        assert "[ bonds ]" in remaining

    def test_no_atomtypes_returns_empty_block_and_unchanged_text(self):
        itp = "[ moleculetype ]\nLIG 3\n[ atoms ]\n1 opls_100 1 LIG C1 1 0.0 12.0\n"
        block, remaining = extract_atomtypes_section(itp)
        assert block == ""
        assert remaining == itp

    def test_atomtypes_block_includes_header_line(self):
        block, _ = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        assert block.strip().startswith("[ atomtypes ]")

    def test_round_trip_preserves_content(self):
        block, remaining = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        reassembled = block + remaining
        # All original content must still be present (possibly reordered)
        for keyword in ["opls_100", "E20", "[ bonds ]"]:
            assert keyword in reassembled

    def test_atomtypes_only_file(self):
        text = "[ atomtypes ]\nopls_1 C 12.0 0.0 A 3.5E-01 2.8E-01\n"
        block, remaining = extract_atomtypes_section(text)
        assert "opls_1" in block
        assert "opls_1" not in remaining


# ═══════════════════════════════════════════════════════════════════════════════
# remove_atomtypes_from_itp
# ═══════════════════════════════════════════════════════════════════════════════

class TestRemoveAtomtypesFromItp:
    def test_output_file_created(self, tmp_path):
        src = tmp_path / "in.itp"
        src.write_text(_LIGAND_ITP_WITH_ATOMTYPES)
        out = tmp_path / "out.itp"
        remove_atomtypes_from_itp(src, out)
        assert out.exists()

    def test_output_has_no_atomtypes(self, tmp_path):
        src = tmp_path / "in.itp"
        src.write_text(_LIGAND_ITP_WITH_ATOMTYPES)
        out = tmp_path / "out.itp"
        remove_atomtypes_from_itp(src, out)
        assert "[ atomtypes ]" not in out.read_text()

    def test_output_keeps_moleculetype(self, tmp_path):
        src = tmp_path / "in.itp"
        src.write_text(_LIGAND_ITP_WITH_ATOMTYPES)
        out = tmp_path / "out.itp"
        remove_atomtypes_from_itp(src, out)
        assert "E20" in out.read_text()

    def test_noop_when_no_atomtypes(self, tmp_path):
        text = "[ moleculetype ]\nLIG 3\n"
        src = tmp_path / "in.itp"
        src.write_text(text)
        out = tmp_path / "out.itp"
        remove_atomtypes_from_itp(src, out)
        assert out.read_text() == text


# ═══════════════════════════════════════════════════════════════════════════════
# split_topol_top
# ═══════════════════════════════════════════════════════════════════════════════

class TestSplitTopolTop:
    def test_writes_protein_itp(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        split_topol_top(top, tmp_path)
        assert (tmp_path / "protein.itp").exists()

    def test_returns_protein_mol_name(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        mol_name, _ = split_topol_top(top, tmp_path)
        assert mol_name == "Protein_chain_A"

    def test_protein_itp_contains_moleculetype(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        split_topol_top(top, tmp_path)
        content = (tmp_path / "protein.itp").read_text()
        assert "[ moleculetype ]" in content

    def test_protein_itp_contains_atoms(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        split_topol_top(top, tmp_path)
        content = (tmp_path / "protein.itp").read_text()
        assert "[ atoms ]" in content

    def test_protein_itp_does_not_contain_system(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        split_topol_top(top, tmp_path)
        content = (tmp_path / "protein.itp").read_text()
        assert "[ system ]" not in content

    def test_water_ions_block_contains_spce(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        _, water_ions = split_topol_top(top, tmp_path)
        assert "spce.itp" in water_ions

    def test_water_ions_block_contains_ions(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        _, water_ions = split_topol_top(top, tmp_path)
        assert "ions.itp" in water_ions

    def test_custom_protein_itp_name(self, tmp_path):
        top = tmp_path / "topol.top"
        top.write_text(_MINIMAL_TOPOL_TOP)
        split_topol_top(top, tmp_path, protein_itp_name="ACHE.itp")
        assert (tmp_path / "ACHE.itp").exists()

    def test_raises_on_missing_moleculetype(self, tmp_path):
        bad = "#include \"oplsaa.ff/forcefield.itp\"\n#include \"oplsaa.ff/spce.itp\"\n"
        top = tmp_path / "topol.top"
        top.write_text(bad)
        with pytest.raises(ValueError, match="moleculetype"):
            split_topol_top(top, tmp_path)

    def test_raises_on_missing_water_include(self, tmp_path):
        bad = (
            "#include \"oplsaa.ff/forcefield.itp\"\n"
            "[ moleculetype ]\nProtein 3\n[ atoms ]\n1 opls_1 1 ALA N 1 0.0\n"
        )
        top = tmp_path / "topol.top"
        top.write_text(bad)
        with pytest.raises(ValueError, match="water"):
            split_topol_top(top, tmp_path)


# ═══════════════════════════════════════════════════════════════════════════════
# generate_topol_top
# ═══════════════════════════════════════════════════════════════════════════════

class TestGenerateTopolTop:
    def _gen(self, tmp_path, water_ions_block="") -> Path:
        return generate_topol_top(
            out_dir=tmp_path,
            forcefield="oplsaa",
            water_model="spce",
            protein_itp_name="protein.itp",
            ligand_itp_name="E20.itp",
            ligand_atomtypes_itp_name="ligand_atomtypes.itp",
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="E20",
            water_ions_block=water_ions_block,
        )

    def test_creates_topol_top(self, tmp_path):
        p = self._gen(tmp_path)
        assert p.exists()
        assert p.name == "topol.top"

    def test_includes_forcefield_first(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        ff_pos = text.index("forcefield.itp")
        at_pos = text.index("ligand_atomtypes.itp")
        assert ff_pos < at_pos

    def test_ligand_atomtypes_before_ligand_itp(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        at_pos = text.index("ligand_atomtypes.itp")
        lig_pos = text.index("E20.itp")
        assert at_pos < lig_pos, "atomtypes must come before ligand itp"

    def test_protein_itp_before_ligand_itp(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        prot_pos = text.index("protein.itp")
        lig_pos = text.index("E20.itp")
        assert prot_pos < lig_pos

    def test_molecules_section_contains_both(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        assert "Protein_chain_A" in text
        assert "E20" in text

    def test_both_in_molecules_with_count_1(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        assert "Protein_chain_A           1" in text
        assert "E20            1" in text

    def test_default_water_ions_block_has_spce(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        assert "spce.itp" in text

    def test_default_water_ions_block_has_ions(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        assert "ions.itp" in text

    def test_custom_water_ions_block_used_verbatim(self, tmp_path):
        custom = '#include "charmm36.ff/tip3p.itp"\n#include "charmm36.ff/ions.itp"'
        text = self._gen(tmp_path, water_ions_block=custom).read_text()
        assert "tip3p.itp" in text
        assert "charmm36.ff" in text

    def test_system_section_present(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        assert "[ system ]" in text

    def test_molecules_section_after_ions(self, tmp_path):
        text = self._gen(tmp_path).read_text()
        ions_pos = text.index("ions.itp")
        mol_pos = text.index("[ molecules ]")
        assert ions_pos < mol_pos


# ═══════════════════════════════════════════════════════════════════════════════
# merge_gro_files
# ═══════════════════════════════════════════════════════════════════════════════

class TestMergeGroFiles:
    def test_creates_complex_gro(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        assert out.exists()

    def test_total_atom_count_returned(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        total = merge_gro_files(pg, lg, tmp_path / "complex.gro")
        assert total == 5 + 3  # 5 protein + 3 ligand atoms

    def test_complex_gro_atom_count_header(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        gro = parse_gro(out)
        assert gro.atom_count == 8

    def test_complex_gro_has_correct_lines(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        gro = parse_gro(out)
        assert len(gro.atoms) == 8

    def test_box_vector_from_protein(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        gro = parse_gro(out)
        prot = parse_gro(pg)
        assert gro.box == prot.box

    def test_atom_numbers_sequential(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        gro = parse_gro(out)
        for expected, atom in enumerate(gro.atoms, start=1):
            assert atom.atom_number == expected

    def test_protein_residues_present(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        gro = parse_gro(out)
        resnames = {a.residue_name for a in gro.atoms}
        assert "ALA" in resnames

    def test_ligand_residues_present(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out)
        gro = parse_gro(out)
        resnames = {a.residue_name for a in gro.atoms}
        assert "E20" in resnames

    def test_title_written(self, tmp_path):
        pg = tmp_path / "protein.gro"
        lg = tmp_path / "ligand.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)
        lg.write_text(_MINIMAL_LIGAND_GRO)
        out = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, out, title="My Complex")
        gro = parse_gro(out)
        assert gro.title == "My Complex"


# ═══════════════════════════════════════════════════════════════════════════════
# validate_system
# ═══════════════════════════════════════════════════════════════════════════════

class TestValidateSystem:
    def _write_fixtures(self, tmp_path) -> dict:
        """Write all necessary files for a valid system."""
        # protein.gro
        pg = tmp_path / "protein.gro"
        pg.write_text(_MINIMAL_PROTEIN_GRO)

        # ligand.gro
        lg = tmp_path / "ligand.gro"
        lg.write_text(_MINIMAL_LIGAND_GRO)

        # complex.gro
        cg = tmp_path / "complex.gro"
        merge_gro_files(pg, lg, cg)

        # ligand.itp (without atomtypes — as it appears in out_dir)
        lig_itp = tmp_path / "E20.itp"
        _, cleaned = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        lig_itp.write_text(cleaned)

        # ligand_atomtypes.itp
        at_itp = tmp_path / "ligand_atomtypes.itp"
        block, _ = extract_atomtypes_section(_LIGAND_ITP_WITH_ATOMTYPES)
        at_itp.write_text(block)

        # topol.top
        top = generate_topol_top(
            out_dir=tmp_path,
            forcefield="oplsaa",
            water_model="spce",
            protein_itp_name="protein.itp",
            ligand_itp_name="E20.itp",
            ligand_atomtypes_itp_name="ligand_atomtypes.itp",
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="E20",
        )

        return {
            "complex_gro": cg,
            "ligand_itp": lig_itp,
            "atomtypes_itp": at_itp,
            "topol_top": top,
        }

    def test_valid_system_no_errors(self, tmp_path):
        f = self._write_fixtures(tmp_path)
        errors = validate_system(
            out_dir=tmp_path,
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="E20",
            ligand_itp_path=f["ligand_itp"],
            complex_gro_path=f["complex_gro"],
            topol_top_path=f["topol_top"],
            ligand_atomtypes_itp_path=f["atomtypes_itp"],
            run_grompp=False,
        )
        assert errors == []

    def test_mol_name_mismatch_raises_error(self, tmp_path):
        f = self._write_fixtures(tmp_path)
        errors = validate_system(
            out_dir=tmp_path,
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="WRONG",  # intentional mismatch
            ligand_itp_path=f["ligand_itp"],
            complex_gro_path=f["complex_gro"],
            topol_top_path=f["topol_top"],
            ligand_atomtypes_itp_path=f["atomtypes_itp"],
            run_grompp=False,
        )
        assert any("mismatch" in e.lower() for e in errors)

    def test_missing_atomtypes_itp_raises_error(self, tmp_path):
        f = self._write_fixtures(tmp_path)
        f["atomtypes_itp"].unlink()
        errors = validate_system(
            out_dir=tmp_path,
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="E20",
            ligand_itp_path=f["ligand_itp"],
            complex_gro_path=f["complex_gro"],
            topol_top_path=f["topol_top"],
            ligand_atomtypes_itp_path=f["atomtypes_itp"],
            run_grompp=False,
        )
        assert any("atomtypes" in e.lower() for e in errors)

    def test_atomtypes_before_ligand_itp_required(self, tmp_path):
        f = self._write_fixtures(tmp_path)
        # Write a topol.top with WRONG include order (ligand before atomtypes)
        bad_top = tmp_path / "topol.top"
        bad_top.write_text(
            '#include "oplsaa.ff/forcefield.itp"\n'
            '#include "E20.itp"\n'
            '#include "ligand_atomtypes.itp"\n'
            '#include "protein.itp"\n'
            "[ system ]\nComplex\n[ molecules ]\nProtein 1\nE20 1\n"
        )
        errors = validate_system(
            out_dir=tmp_path,
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="E20",
            ligand_itp_path=f["ligand_itp"],
            complex_gro_path=f["complex_gro"],
            topol_top_path=bad_top,
            ligand_atomtypes_itp_path=f["atomtypes_itp"],
            run_grompp=False,
        )
        assert any("order" in e.lower() or "before" in e.lower() for e in errors)

    def test_wrong_atom_count_in_gro(self, tmp_path):
        f = self._write_fixtures(tmp_path)
        # Corrupt complex.gro by changing the atom count header to a wrong value.
        # The parser will raise when declared count != actual atom lines.
        lines = f["complex_gro"].read_text().splitlines()
        lines[1] = "   99"  # declared 99, actual 8 → parse_gro raises
        f["complex_gro"].write_text("\n".join(lines) + "\n")
        errors = validate_system(
            out_dir=tmp_path,
            protein_mol_name="Protein_chain_A",
            ligand_mol_name="E20",
            ligand_itp_path=f["ligand_itp"],
            complex_gro_path=f["complex_gro"],
            topol_top_path=f["topol_top"],
            ligand_atomtypes_itp_path=f["atomtypes_itp"],
            run_grompp=False,
        )
        # Any error about the GRO file is acceptable (parse error or count mismatch)
        assert any("gro" in e.lower() or "atom" in e.lower() for e in errors)


# ═══════════════════════════════════════════════════════════════════════════════
# detect_ligand_residues (from prepare.py)
# ═══════════════════════════════════════════════════════════════════════════════

class TestDetectLigandResidues:
    def test_finds_hetatm_residue(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = detect_ligand_residues(pdb)
        assert "E20" in result

    def test_excludes_standard_aa(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = detect_ligand_residues(pdb)
        assert "ALA" not in result

    def test_returns_sorted_list(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        content = (
            "HETATM    1  C1  ZZZ A 200      1.0   1.0   1.0  1.00  0.00           C\n"
            "HETATM    2  O1  AAA A 201      2.0   2.0   2.0  1.00  0.00           O\n"
        )
        pdb.write_text(content)
        result = detect_ligand_residues(pdb)
        assert result == sorted(result)

    def test_excludes_water(self, tmp_path):
        pdb = tmp_path / "wat.pdb"
        pdb.write_text("HETATM    1  O   HOH A   1       0.0   0.0   0.0  1.00\n")
        result = detect_ligand_residues(pdb)
        assert "HOH" not in result

    def test_empty_when_only_standard(self, tmp_path):
        pdb = tmp_path / "prot.pdb"
        pdb.write_text("ATOM      1  N   ALA A   1       0.0   0.0   0.0\n")
        result = detect_ligand_residues(pdb)
        assert result == []


# ═══════════════════════════════════════════════════════════════════════════════
# extract_ligand_from_complex (from prepare.py)
# ═══════════════════════════════════════════════════════════════════════════════

class TestExtractLigandFromComplex:
    def test_success(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.success is True

    def test_ligand_pdb_created(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.ligand_pdb is not None
        assert result.ligand_pdb.exists()

    def test_protein_pdb_created(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.protein_pdb is not None
        assert result.protein_pdb.exists()

    def test_report_yaml_created(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.report_path is not None
        assert result.report_path.exists()
        assert result.report_path.suffix == ".yaml"

    def test_ligand_atom_count(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.ligand_atom_count == 3  # C1, O1, H1

    def test_protein_atom_count(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.protein_atom_count == 3  # N, CA, C

    def test_ligand_pdb_contains_only_ligand_records(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        content = result.ligand_pdb.read_text()
        assert "ALA" not in content

    def test_protein_pdb_does_not_contain_ligand_resname(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        content = result.protein_pdb.read_text()
        assert "E20" not in content

    def test_missing_complex_pdb_returns_failure(self, tmp_path):
        result = extract_ligand_from_complex(
            tmp_path / "ghost.pdb", "E20", tmp_path / "out"
        )
        assert result.success is False
        assert result.error is not None

    def test_wrong_resname_returns_failure(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "XYZ", tmp_path / "out")
        assert result.success is False
        assert "XYZ" in result.error

    def test_error_suggests_available_residues(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "XYZ", tmp_path / "out")
        assert "E20" in result.error  # should mention the actual ligand

    def test_conect_records_included_in_ligand_pdb(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        content = result.ligand_pdb.read_text()
        assert "CONECT" in content

    def test_ligand_resname_stored_in_result(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_MINIMAL_DOCKED_COMPLEX_PDB)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.ligand_resname == "E20"


# ═══════════════════════════════════════════════════════════════════════════════
# Hydrogen detection (_has_hydrogens)
# ═══════════════════════════════════════════════════════════════════════════════

# PDB lines used across hydrogen tests
_HETATM_C  = "HETATM    4  C1  E20 A 201      15.000  15.000  15.000  1.00  0.00           C"
_HETATM_O  = "HETATM    5  O1  E20 A 201      15.600  15.000  15.000  1.00  0.00           O"
_HETATM_H  = "HETATM    6  H1  E20 A 201      15.900  15.300  15.000  1.00  0.00           H"
_HETATM_H_NO_ELEM = "HETATM    7  H2  E20 A 201      16.000  15.000  15.000  1.00  0.00"

# Complex PDB with explicit hydrogens on the ligand
_COMPLEX_WITH_H = (
    "ATOM      1  N   ALA A   1       7.500   7.500   7.500  1.00  0.00           N\n"
    f"{_HETATM_C}\n"
    f"{_HETATM_O}\n"
    f"{_HETATM_H}\n"
    "END\n"
)

# Complex PDB with no hydrogens on the ligand
_COMPLEX_NO_H = (
    "ATOM      1  N   ALA A   1       7.500   7.500   7.500  1.00  0.00           N\n"
    f"{_HETATM_C}\n"
    f"{_HETATM_O}\n"
    "END\n"
)

# E20-like: 28 heavy atoms + 1 H — chemically incomplete, ratio 1/28 = 0.036 < 0.15
_COMPLEX_E20_LIKE = (
    "ATOM      1  N   ALA A   1       7.500   7.500   7.500  1.00  0.00           N\n"
    + "".join(
        f"HETATM {i+2:4d}  C{i+1:<2} E20 A 201  {15.0 + i * 0.3:8.3f}  15.000  15.000  1.00  0.00           C\n"
        for i in range(28)
    )
    + "HETATM   30  H1  E20 A 201      15.900  15.300  15.000  1.00  0.00           H\n"
    + "END\n"
)

# Lines for _COMPLEX_E20_LIKE ligand records only (for unit-testing status functions)
_E20_LIGAND_LINES: list[str] = [
    f"HETATM {i+2:4d}  C{i+1:<2} E20 A 201  {15.0 + i * 0.3:8.3f}  15.000  15.000  1.00  0.00           C"
    for i in range(28)
] + ["HETATM   30  H1  E20 A 201      15.900  15.300  15.000  1.00  0.00           H"]


def _mock_obabel_success(cmd, *args, **kwargs):
    """side_effect for subprocess.run that simulates a successful obabel run."""
    # Extract the -O output path from the command
    try:
        o_idx = list(cmd).index("-O")
        out_file = Path(cmd[o_idx + 1])
    except (ValueError, IndexError):
        return MagicMock(returncode=0, stderr="")

    out_file.write_text(
        "HETATM    1  C1  E20 A 201      15.000  15.000  15.000  1.00  0.00           C\n"
        "HETATM    2  H1  E20 A 201      15.300  15.000  15.000  1.00  0.00           H\n"
        "END\n"
    )
    return MagicMock(returncode=0, stderr="")


def _mock_obabel_failure(cmd, *args, **kwargs):
    """side_effect for subprocess.run that simulates an obabel failure."""
    return MagicMock(returncode=1, stderr="Open Babel Error: could not read molecule")


# Helpers that patch at the hydrogenation module level (new mock paths post-refactor)
_RDKIT_AVAIL = "ligand.hydrogenation._rdkit_available"
_OBABEL_AVAIL = "ligand.hydrogenation._obabel_available"
_SUBPROC_RUN = "ligand.hydrogenation.subprocess.run"


class TestHasHydrogens:
    def test_detects_h_by_element_column(self):
        assert _has_hydrogens([_HETATM_H]) is True

    def test_detects_h_by_atom_name_when_no_element_col(self):
        assert _has_hydrogens([_HETATM_H_NO_ELEM]) is True

    def test_no_h_for_heavy_atoms_only(self):
        assert _has_hydrogens([_HETATM_C, _HETATM_O]) is False

    def test_empty_list_is_false(self):
        assert _has_hydrogens([]) is False

    def test_non_atom_lines_ignored(self):
        assert _has_hydrogens(["REMARK H-bond donor", "CONECT    4    5"]) is False

    def test_deuterium_treated_as_hydrogen(self):
        d_line = "HETATM    7  D1  LIG A 201      15.000  15.000  15.000  1.00  0.00           D"
        assert _has_hydrogens([d_line]) is True

    def test_carbon_not_confused_with_hydrogen(self):
        assert _has_hydrogens([_HETATM_C]) is False


# ═══════════════════════════════════════════════════════════════════════════════
# Hydrogen handling in extract_ligand_from_complex
# ═══════════════════════════════════════════════════════════════════════════════

class TestHydrogenHandling:
    # ── Ligand with hydrogens (happy path) ───────────────────────────────────

    def test_with_h_has_hydrogens_true(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.has_hydrogens is True

    def test_with_h_no_hydrogenation_performed(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_performed is False

    def test_with_h_backend_is_none(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_backend == "none"

    def test_with_h_no_hydrogenated_pdb(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenated_ligand_pdb is None

    def test_with_h_no_h_warning(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert not any("hydrogen" in w.lower() for w in result.warnings)

    def test_with_h_hydrogenation_not_required(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_required is False

    def test_with_h_recommended_input_is_raw_pdb(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.recommended_ligpargen_input == result.ligand_pdb

    def test_with_h_n_hydrogen_atoms_positive(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.n_hydrogen_atoms == 1  # one H1 atom in _COMPLEX_WITH_H

    # ── Ligand without H, obabel available ───────────────────────────────────

    def test_no_h_obabel_available_performs_hydrogenation(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_performed is True

    def test_no_h_obabel_creates_h_file(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenated_ligand_pdb is not None
        assert result.hydrogenated_ligand_pdb.exists()
        assert result.hydrogenated_ligand_pdb.name == "ligand_for_ligpargen_H.pdb"

    def test_no_h_obabel_backend_set_to_openbabel(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_backend == "openbabel"

    def test_no_h_obabel_success_is_true(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.success is True

    def test_no_h_obabel_has_hydrogens_is_false_on_source(self, tmp_path):
        # has_hydrogens reflects the ORIGINAL extracted file, not the protonated one
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.has_hydrogens is False

    def test_no_h_obabel_recommended_input_is_h_pdb(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.recommended_ligpargen_input == result.hydrogenated_ligand_pdb

    def test_no_h_obabel_confidence_set(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_confidence > 0.0

    # ── Ligand without H, obabel fails ───────────────────────────────────────

    def test_no_h_obabel_fails_backend_is_openbabel(self, tmp_path):
        # Backend name reflects what was attempted, not whether it succeeded
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_failure),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_backend == "openbabel"

    def test_no_h_obabel_fails_no_h_file(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_failure),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenated_ligand_pdb is None

    def test_no_h_obabel_fails_hydrogenation_required(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_failure),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_required is True

    # ── Ligand without H, both backends unavailable ───────────────────────────

    def test_no_h_both_unavailable_has_hydrogens_false(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.has_hydrogens is False

    def test_no_h_both_unavailable_backend_manual_required(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_backend == "manual_required"

    def test_no_h_both_unavailable_emits_warning(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert any("hydrogen" in w.lower() for w in result.warnings)

    def test_no_h_both_unavailable_warning_mentions_install(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        combined = " ".join(result.warnings).lower()
        assert "rdkit" in combined or "openbabel" in combined or "obabel" in combined

    def test_no_h_both_unavailable_no_h_file(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenated_ligand_pdb is None

    def test_no_h_both_unavailable_success_still_true(self, tmp_path):
        # Extraction succeeded (files written), even though H are missing
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.success is True
        assert result.hydrogenation_required is True

    def test_no_h_both_unavailable_recommended_input_none(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.recommended_ligpargen_input is None

    # ── hydrogenation_mode="none" ─────────────────────────────────────────────

    def test_hydrogenation_mode_none_with_no_h_skipped(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out", hydrogenation_mode="none")
        assert result.hydrogenation_backend == "skipped"
        assert result.hydrogenation_required is True
        assert result.hydrogenation_performed is False

    def test_hydrogenation_mode_none_with_h_present_normal(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out", hydrogenation_mode="none")
        assert result.has_hydrogens is True
        assert result.hydrogenation_required is False

    def test_hydrogenation_mode_none_warning_mentions_skipped(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out", hydrogenation_mode="none")
        combined = " ".join(result.warnings).lower()
        assert "skipped" in combined or "none" in combined

    # ── Report YAML fields ────────────────────────────────────────────────────

    def test_report_has_has_hydrogens_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "has_hydrogens" in report

    def test_report_has_hydrogens_true_when_present(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["has_hydrogens"] is True

    def test_report_has_hydrogens_false_when_absent(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["has_hydrogens"] is False

    def test_report_n_hydrogen_atoms_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "n_hydrogen_atoms" in report
        assert report["n_hydrogen_atoms"] >= 0

    def test_report_hydrogenation_required_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "hydrogenation_required" in report
        assert report["hydrogenation_required"] is False

    def test_report_hydrogenation_performed_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "hydrogenation_performed" in report

    def test_report_hydrogenation_backend_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "hydrogenation_backend" in report

    def test_report_hydrogenation_backend_none_with_h(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["hydrogenation_backend"] == "none"

    def test_report_hydrogenation_backend_openbabel_when_ran(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["hydrogenation_backend"] == "openbabel"

    def test_report_hydrogenation_confidence_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "hydrogenation_confidence" in report
        assert isinstance(report["hydrogenation_confidence"], float)

    def test_report_recommended_ligpargen_input_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "recommended_ligpargen_input" in report
        assert report["recommended_ligpargen_input"] is not None

    def test_report_hydrogenated_ligand_pdb_null_without_backend(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["hydrogenated_ligand_pdb"] is None

    def test_report_hydrogenated_ligand_pdb_set_after_obabel(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["hydrogenated_ligand_pdb"] is not None

    def test_report_next_steps_recommend_h_file_after_obabel(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        next_steps_text = " ".join(report.get("next_steps", []))
        # Should recommend the _H.pdb file, not the raw one
        assert "_H.pdb" in next_steps_text or "ligand_for_ligpargen_H" in next_steps_text

    def test_report_next_steps_warn_when_manual_required(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        next_steps_text = " ".join(report.get("next_steps", []))
        assert "warning" in next_steps_text.lower() or "do not" in next_steps_text.lower()


# ═══════════════════════════════════════════════════════════════════════════════
# CLI prepare command
# ═══════════════════════════════════════════════════════════════════════════════

from typer.testing import CliRunner as _CliRunner
from cli import cli as _cli

_runner = _CliRunner(mix_stderr=False)


class TestPrepareCLI:
    def test_prepare_help(self):
        result = _runner.invoke(_cli, ["ligand", "prepare", "--help"])
        assert result.exit_code == 0
        assert "COMPLEX_PDB" in result.output or "complex_pdb" in result.output.lower()

    def test_prepare_help_shows_hydrogenation_option(self):
        result = _runner.invoke(_cli, ["ligand", "prepare", "--help"])
        assert result.exit_code == 0
        assert "hydrogenation" in result.output.lower()

    def test_prepare_missing_file_exits_nonzero(self, tmp_path):
        result = _runner.invoke(
            _cli, ["ligand", "prepare", str(tmp_path / "ghost.pdb")]
        )
        assert result.exit_code != 0

    def test_prepare_with_h_exits_zero(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = _runner.invoke(
            _cli,
            ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
             "--out", str(tmp_path / "out")],
        )
        assert result.exit_code == 0

    def test_prepare_manual_required_exits_nonzero(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        assert result.exit_code != 0

    def test_prepare_manual_required_output_mentions_hydrogen(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        assert "hydrogen" in result.output.lower()

    def test_prepare_obabel_success_exits_zero(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        assert result.exit_code == 0

    def test_prepare_obabel_success_recommends_h_file(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        # The output should mention the _H.pdb file as the one to submit
        assert "_H.pdb" in result.output or "ligand_for_ligpargen_H" in result.output

    def test_prepare_with_h_shows_hydrogens_present(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = _runner.invoke(
            _cli,
            ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
             "--out", str(tmp_path / "out")],
        )
        assert "present" in result.output.lower() or "hydrogen" in result.output.lower()


# ═══════════════════════════════════════════════════════════════════════════════
# --hydrogenation CLI option
# ═══════════════════════════════════════════════════════════════════════════════

class TestHydrogenationCLIOption:
    def test_hydrogenation_none_no_h_exits_nonzero(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        result = _runner.invoke(
            _cli,
            ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
             "--out", str(tmp_path / "out"), "--hydrogenation", "none"],
        )
        assert result.exit_code != 0

    def test_hydrogenation_none_no_h_output_mentions_hydrogen(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        result = _runner.invoke(
            _cli,
            ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
             "--out", str(tmp_path / "out"), "--hydrogenation", "none"],
        )
        assert "hydrogen" in result.output.lower()

    def test_hydrogenation_none_unknown_status_exits_nonzero(self, tmp_path):
        # _COMPLEX_WITH_H has only 1 H on 2 heavy atoms — status "unknown".
        # --hydrogenation none blocks whenever status is not "complete".
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = _runner.invoke(
            _cli,
            ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
             "--out", str(tmp_path / "out"), "--hydrogenation", "none"],
        )
        assert result.exit_code != 0

    def test_hydrogenation_none_complete_status_exits_zero(self, tmp_path):
        # When status is provably "complete", --none must not block.
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        with patch("ligand.prepare._determine_hydrogenation_status", return_value=("complete", True)):
            result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out"), "--hydrogenation", "none"],
            )
        assert result.exit_code == 0

    def test_hydrogenation_openbabel_forced(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with (
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out"), "--hydrogenation", "openbabel"],
            )
        assert result.exit_code == 0


# ═══════════════════════════════════════════════════════════════════════════════
# HydrogenationBackend module tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestHydrogenationBackendModule:
    def test_select_backend_none_returns_none(self):
        from ligand.hydrogenation import select_backend
        assert select_backend("none") is None

    def test_select_backend_auto_rdkit_when_available(self):
        from ligand.hydrogenation import select_backend, RDKitHydrogenationBackend
        with patch(_RDKIT_AVAIL, return_value=True):
            backend = select_backend("auto")
        assert isinstance(backend, RDKitHydrogenationBackend)

    def test_select_backend_auto_obabel_when_rdkit_unavailable(self):
        from ligand.hydrogenation import select_backend, OpenBabelHydrogenationBackend
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=True):
            backend = select_backend("auto")
        assert isinstance(backend, OpenBabelHydrogenationBackend)

    def test_select_backend_auto_manual_when_both_unavailable(self):
        from ligand.hydrogenation import select_backend, ManualRequiredBackend
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            backend = select_backend("auto")
        assert isinstance(backend, ManualRequiredBackend)

    def test_select_backend_rdkit_forced(self):
        from ligand.hydrogenation import select_backend, RDKitHydrogenationBackend
        with patch(_RDKIT_AVAIL, return_value=True):
            backend = select_backend("rdkit")
        assert isinstance(backend, RDKitHydrogenationBackend)

    def test_select_backend_rdkit_forced_falls_to_manual_when_unavailable(self):
        from ligand.hydrogenation import select_backend, ManualRequiredBackend
        with patch(_RDKIT_AVAIL, return_value=False):
            backend = select_backend("rdkit")
        assert isinstance(backend, ManualRequiredBackend)

    def test_select_backend_openbabel_forced(self):
        from ligand.hydrogenation import select_backend, OpenBabelHydrogenationBackend
        with patch(_OBABEL_AVAIL, return_value=True):
            backend = select_backend("openbabel")
        assert isinstance(backend, OpenBabelHydrogenationBackend)

    def test_select_backend_openbabel_forced_falls_to_manual_when_unavailable(self):
        from ligand.hydrogenation import select_backend, ManualRequiredBackend
        with patch(_OBABEL_AVAIL, return_value=False):
            backend = select_backend("openbabel")
        assert isinstance(backend, ManualRequiredBackend)

    def test_manual_backend_always_fails(self):
        from ligand.hydrogenation import ManualRequiredBackend
        backend = ManualRequiredBackend()
        result = backend.add_hydrogens(Path("/dev/null"), Path("/dev/null"))
        assert result.success is False
        assert result.backend_name == "manual_required"

    def test_manual_backend_is_always_available(self):
        from ligand.hydrogenation import ManualRequiredBackend
        assert ManualRequiredBackend().is_available() is True

    def test_rdkit_backend_name(self):
        from ligand.hydrogenation import RDKitHydrogenationBackend
        assert RDKitHydrogenationBackend.name == "rdkit"

    def test_obabel_backend_name(self):
        from ligand.hydrogenation import OpenBabelHydrogenationBackend
        assert OpenBabelHydrogenationBackend.name == "openbabel"

    def test_rdkit_backend_unavailable_when_not_installed(self):
        from ligand.hydrogenation import RDKitHydrogenationBackend
        with patch(_RDKIT_AVAIL, return_value=False):
            assert RDKitHydrogenationBackend().is_available() is False

    def test_obabel_backend_unavailable_when_not_in_path(self):
        from ligand.hydrogenation import OpenBabelHydrogenationBackend
        with patch(_OBABEL_AVAIL, return_value=False):
            assert OpenBabelHydrogenationBackend().is_available() is False

    def test_obabel_backend_add_h_success(self, tmp_path):
        from ligand.hydrogenation import OpenBabelHydrogenationBackend
        in_pdb = tmp_path / "in.pdb"
        in_pdb.write_text(_HETATM_C + "\n" + _HETATM_O + "\nEND\n")
        out_pdb = tmp_path / "out.pdb"
        with (
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = OpenBabelHydrogenationBackend().add_hydrogens(in_pdb, out_pdb)
        assert result.success is True
        assert result.n_hydrogen_atoms > 0
        assert result.confidence > 0.0

    def test_obabel_backend_add_h_failure(self, tmp_path):
        from ligand.hydrogenation import OpenBabelHydrogenationBackend
        in_pdb = tmp_path / "in.pdb"
        in_pdb.write_text(_HETATM_C + "\nEND\n")
        out_pdb = tmp_path / "out.pdb"
        with (
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_failure),
        ):
            result = OpenBabelHydrogenationBackend().add_hydrogens(in_pdb, out_pdb)
        assert result.success is False
        assert result.warning is not None


# ═══════════════════════════════════════════════════════════════════════════════
# Hydrogenation status semantics  (Task 4 — E20 regression)
# ═══════════════════════════════════════════════════════════════════════════════

class TestHydrationStatus:
    """Tests for _count_heavy_atoms, _determine_hydrogenation_status, and
    the new fields n_heavy_atoms / hydrogenation_status / hydrogenation_complete."""

    # ── Unit tests for _count_heavy_atoms ────────────────────────────────────

    def test_count_heavy_atoms_no_h(self):
        assert _count_heavy_atoms([_HETATM_C, _HETATM_O]) == 2

    def test_count_heavy_atoms_ignores_h(self):
        assert _count_heavy_atoms([_HETATM_C, _HETATM_O, _HETATM_H]) == 2

    def test_count_heavy_atoms_empty(self):
        assert _count_heavy_atoms([]) == 0

    # ── Unit tests for _determine_hydrogenation_status ────────────────────────

    def test_status_missing_when_zero_h(self):
        status, complete = _determine_hydrogenation_status([], n_h_atoms=0, n_heavy_atoms=5)
        assert status == "missing"
        assert complete is False

    def test_status_incomplete_for_e20_ratio(self):
        # 1 H / 28 heavy = 0.036 < 0.15 → "incomplete"
        status, complete = _determine_hydrogenation_status(
            _E20_LIGAND_LINES, n_h_atoms=1, n_heavy_atoms=28
        )
        assert status == "incomplete"
        assert complete is False

    def test_status_unknown_for_plausible_ratio(self):
        # 1 H / 2 heavy = 0.5 >= 0.15, no RDKit → "unknown"
        lines = [_HETATM_C, _HETATM_O, _HETATM_H]
        status, complete = _determine_hydrogenation_status(lines, n_h_atoms=1, n_heavy_atoms=2)
        assert status == "unknown"
        assert complete is False

    def test_status_incomplete_at_threshold_boundary(self):
        # ratio = 1/7 ≈ 0.143 < 0.15 → "incomplete"
        lines = (
            [f"HETATM {i+1:4d}  C{i}  LIG A 201      1.000   1.000   1.000  1.00  0.00           C"
             for i in range(7)]
            + ["HETATM    8  H1  LIG A 201      1.100   1.000   1.000  1.00  0.00           H"]
        )
        status, complete = _determine_hydrogenation_status(lines, n_h_atoms=1, n_heavy_atoms=7)
        assert status == "incomplete"
        assert complete is False

    # ── Regression test: E20-like full extraction ─────────────────────────────

    def test_e20_like_classified_incomplete(self, tmp_path):
        """28 heavy atoms + 1 H must be classified as 'incomplete', not 'present'."""
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_status == "incomplete"

    def test_e20_like_complete_is_false(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_complete is False

    def test_e20_like_has_hydrogens_true(self, tmp_path):
        # has_hydrogens = n_h > 0, even if incomplete
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.has_hydrogens is True

    def test_e20_like_n_hydrogen_atoms_is_1(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.n_hydrogen_atoms == 1

    def test_e20_like_n_heavy_atoms_is_28(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.n_heavy_atoms == 28

    def test_e20_like_triggers_hydrogenation(self, tmp_path):
        # status "incomplete" → hydrogenation triggered automatically
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_performed is True

    def test_e20_like_hydrogenation_required_when_no_backend(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_required is True

    def test_e20_like_recommended_input_none_when_not_fixed(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.recommended_ligpargen_input is None

    # ── Status for _COMPLEX_WITH_H (small molecule, ratio okay) ──────────────

    def test_complex_with_h_status_is_unknown(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        with patch(_RDKIT_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_status == "unknown"

    def test_complex_no_h_status_is_missing(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_NO_H)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        assert result.hydrogenation_status == "missing"

    # ── New YAML report fields ────────────────────────────────────────────────

    def test_report_n_heavy_atoms_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "n_heavy_atoms" in report
        assert isinstance(report["n_heavy_atoms"], int)
        assert report["n_heavy_atoms"] >= 0

    def test_report_hydrogenation_status_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "hydrogenation_status" in report
        assert report["hydrogenation_status"] in ("complete", "incomplete", "missing", "unknown")

    def test_report_hydrogenation_complete_field(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_WITH_H)
        result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert "hydrogenation_complete" in report
        assert isinstance(report["hydrogenation_complete"], bool)

    def test_report_e20_like_status_incomplete(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            result = extract_ligand_from_complex(pdb, "E20", tmp_path / "out")
        report = yaml.safe_load(result.report_path.read_text())
        assert report["hydrogenation_status"] == "incomplete"
        assert report["hydrogenation_complete"] is False
        assert report["n_heavy_atoms"] == 28
        assert report["n_hydrogen_atoms"] == 1

    # ── CLI output for E20-like (incomplete) ──────────────────────────────────

    def test_cli_e20_like_shows_incomplete(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=False),
        ):
            cli_result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        assert "incomplete" in cli_result.output.lower()

    def test_cli_e20_like_does_not_say_present(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=False),
        ):
            cli_result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        # "present" must NOT appear as the hydrogen status
        lines = [l for l in cli_result.output.splitlines() if "Hydrogens" in l]
        assert all("present" not in l.lower() for l in lines)

    def test_cli_e20_like_exits_nonzero_when_no_backend(self, tmp_path):
        # incomplete + no backend → hydrogenation_required → blocks
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with patch(_RDKIT_AVAIL, return_value=False), patch(_OBABEL_AVAIL, return_value=False):
            cli_result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        assert cli_result.exit_code != 0

    def test_cli_e20_like_exits_zero_after_obabel_success(self, tmp_path):
        pdb = tmp_path / "complex.pdb"
        pdb.write_text(_COMPLEX_E20_LIKE)
        with (
            patch(_RDKIT_AVAIL, return_value=False),
            patch(_OBABEL_AVAIL, return_value=True),
            patch(_SUBPROC_RUN, side_effect=_mock_obabel_success),
        ):
            cli_result = _runner.invoke(
                _cli,
                ["ligand", "prepare", str(pdb), "--ligand-resname", "E20",
                 "--out", str(tmp_path / "out")],
            )
        assert cli_result.exit_code == 0


# ═══════════════════════════════════════════════════════════════════════════════
# pdb2gmx adaptive -ignh fallback
# ═══════════════════════════════════════════════════════════════════════════════

# Sample pdb2gmx stderr messages used across tests
_IGNH_STDERR = (
    "Fatal error:\n"
    "Atom HD1 in residue HIS 212 was not found in rtp entry HISE\n"
    "For a hydrogen, this can be a different protonation state.\n"
    "Option -ignh will ignore all hydrogens in the input.\n"
    "Remove this hydrogen or change the force field.\n"
)

_NON_H_STDERR = (
    "Fatal error:\n"
    "Residue 'UNK' not found in residue topology database.\n"
    "You can set the environment variable GMXLIB to a directory "
    "with custom residue files.\n"
)

_GMX_WHICH = "ligand.integrate.shutil.which"
_GMX_SUBPROC = "ligand.integrate.subprocess.run"


def _write_pdb2gmx_outputs_from_cmd(cmd: list) -> None:
    """Write minimal pdb2gmx output files by extracting paths from cmd args."""
    for flag, content in [("-o", _MINIMAL_PROTEIN_GRO), ("-p", _MINIMAL_TOPOL_TOP), ("-i", "; posre\n")]:
        try:
            idx = list(cmd).index(flag)
            Path(cmd[idx + 1]).write_text(content)
        except (ValueError, IndexError, OSError):
            pass


class TestPdb2gmxFallback:

    # ── Detection function unit tests ─────────────────────────────────────────

    def test_should_retry_true_when_ignh_line_present(self):
        output = "Fatal error\nOption -ignh will ignore all hydrogens in the input.\n"
        should_retry, reason = _should_retry_with_ignh(output)
        assert should_retry is True
        assert reason  # non-empty; contains the matching line

    def test_should_retry_true_when_protonation_state_line(self):
        output = "Fatal error\nFor a hydrogen, this can be a different protonation state.\n"
        should_retry, _ = _should_retry_with_ignh(output)
        assert should_retry is True

    def test_should_retry_true_for_full_his_mismatch_error(self):
        should_retry, _ = _should_retry_with_ignh(_IGNH_STDERR)
        assert should_retry is True

    def test_should_retry_false_for_missing_residue_error(self):
        should_retry, _ = _should_retry_with_ignh(_NON_H_STDERR)
        assert should_retry is False

    def test_should_retry_false_for_empty_output(self):
        should_retry, _ = _should_retry_with_ignh("")
        assert should_retry is False

    def test_should_retry_false_for_unrelated_error(self):
        output = "Fatal error:\nAtom type 'opls_999' not found in ffnonbonded.itp\n"
        should_retry, _ = _should_retry_with_ignh(output)
        assert should_retry is False

    def test_should_retry_reason_contains_trigger_phrase(self):
        output = _IGNH_STDERR
        _, reason = _should_retry_with_ignh(output)
        assert "ignh" in reason.lower() or "hydrogen" in reason.lower()

    # ── run_pdb2gmx unit tests ────────────────────────────────────────────────

    def test_run_pdb2gmx_success_no_fallback(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_ok = MagicMock(returncode=0, stdout="", stderr="")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, return_value=mock_ok),
        ):
            _, _, _, meta = run_pdb2gmx(pdb, tmp_path / "out")
        assert meta.fallback_used is False
        assert meta.initial_exit_code == 0
        assert meta.final_exit_code == 0

    def test_run_pdb2gmx_success_subprocess_called_once(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_ok = MagicMock(returncode=0, stdout="", stderr="")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, return_value=mock_ok) as spy,
        ):
            run_pdb2gmx(pdb, tmp_path / "out")
        assert spy.call_count == 1

    def test_run_pdb2gmx_h_mismatch_triggers_fallback(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail = MagicMock(returncode=1, stdout="", stderr=_IGNH_STDERR)
        mock_ok = MagicMock(returncode=0, stdout="", stderr="")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, side_effect=[mock_fail, mock_ok]),
        ):
            _, _, _, meta = run_pdb2gmx(pdb, tmp_path / "out")
        assert meta.fallback_used is True
        assert meta.initial_exit_code == 1
        assert meta.final_exit_code == 0

    def test_run_pdb2gmx_h_mismatch_subprocess_called_twice(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail = MagicMock(returncode=1, stdout="", stderr=_IGNH_STDERR)
        mock_ok = MagicMock(returncode=0, stdout="", stderr="")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, side_effect=[mock_fail, mock_ok]) as spy,
        ):
            run_pdb2gmx(pdb, tmp_path / "out")
        assert spy.call_count == 2

    def test_run_pdb2gmx_h_mismatch_ignh_in_fallback_cmd(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail = MagicMock(returncode=1, stdout="", stderr=_IGNH_STDERR)
        mock_ok = MagicMock(returncode=0, stdout="", stderr="")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, side_effect=[mock_fail, mock_ok]),
        ):
            _, _, _, meta = run_pdb2gmx(pdb, tmp_path / "out")
        assert "-ignh" in meta.fallback_command
        assert "-ignh" not in meta.initial_command

    def test_run_pdb2gmx_h_mismatch_initial_error_summary_set(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail = MagicMock(returncode=1, stdout="", stderr=_IGNH_STDERR)
        mock_ok = MagicMock(returncode=0, stdout="", stderr="")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, side_effect=[mock_fail, mock_ok]),
        ):
            _, _, _, meta = run_pdb2gmx(pdb, tmp_path / "out")
        assert meta.initial_error_summary  # non-empty

    def test_run_pdb2gmx_non_h_error_raises(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail = MagicMock(returncode=1, stdout="", stderr=_NON_H_STDERR)
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, return_value=mock_fail),
        ):
            with pytest.raises(RuntimeError, match="pdb2gmx failed"):
                run_pdb2gmx(pdb, tmp_path / "out")

    def test_run_pdb2gmx_non_h_error_no_retry(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail = MagicMock(returncode=1, stdout="", stderr=_NON_H_STDERR)
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, return_value=mock_fail) as spy,
        ):
            try:
                run_pdb2gmx(pdb, tmp_path / "out")
            except RuntimeError:
                pass
        assert spy.call_count == 1

    def test_run_pdb2gmx_fallback_also_fails_raises(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        mock_fail1 = MagicMock(returncode=1, stdout="", stderr=_IGNH_STDERR)
        mock_fail2 = MagicMock(returncode=1, stdout="", stderr="Some other error")
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, side_effect=[mock_fail1, mock_fail2]),
        ):
            with pytest.raises(RuntimeError, match="even with -ignh"):
                run_pdb2gmx(pdb, tmp_path / "out")

    def test_run_pdb2gmx_no_gmx_raises(self, tmp_path):
        pdb = tmp_path / "protein.pdb"
        pdb.write_text("END\n")
        with patch(_GMX_WHICH, return_value=None):
            with pytest.raises(RuntimeError, match="GROMACS"):
                run_pdb2gmx(pdb, tmp_path / "out")

    # ── assemble_system integration tests (mocked pdb2gmx) ───────────────────

    def _pdb2gmx_h_fail_then_success(self, cmd, **kwargs):
        if "-ignh" in list(cmd):
            _write_pdb2gmx_outputs_from_cmd(cmd)
            return MagicMock(returncode=0, stdout="", stderr="")
        return MagicMock(returncode=1, stdout="", stderr=_IGNH_STDERR)

    def _pdb2gmx_clean_success(self, cmd, **kwargs):
        _write_pdb2gmx_outputs_from_cmd(cmd)
        return MagicMock(returncode=0, stdout="", stderr="")

    def _run_assemble(self, tmp_path, pdb2gmx_side_effect):
        from ligand.integrate import assemble_system
        lig_itp = tmp_path / "LIG.itp"
        lig_itp.write_text(_LIGAND_ITP_WITH_ATOMTYPES)
        lig_gro = tmp_path / "LIG.gro"
        lig_gro.write_text(_MINIMAL_LIGAND_GRO)
        prot_pdb = tmp_path / "protein.pdb"
        prot_pdb.write_text("END\n")
        out = tmp_path / "system"
        with (
            patch(_GMX_WHICH, return_value="/usr/bin/gmx"),
            patch(_GMX_SUBPROC, side_effect=pdb2gmx_side_effect),
        ):
            return assemble_system(
                protein_pdb=prot_pdb,
                ligand_itp=lig_itp,
                ligand_gro=lig_gro,
                out_dir=out,
                run_grompp=False,
            )

    def test_assemble_normal_success_no_fallback(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_clean_success)
        assert result.pdb2gmx_fallback_used is False

    def test_assemble_h_mismatch_fallback_used(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_h_fail_then_success)
        assert result.pdb2gmx_fallback_used is True

    def test_report_all_pdb2gmx_fields_present(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_h_fail_then_success)
        assert result.report_path is not None and result.report_path.exists()
        report = yaml.safe_load(result.report_path.read_text())
        for field in (
            "pdb2gmx_initial_attempt_exit_code",
            "pdb2gmx_initial_command",
            "pdb2gmx_initial_error_summary",
            "pdb2gmx_fallback_used",
            "pdb2gmx_fallback_reason",
            "pdb2gmx_fallback_command",
            "pdb2gmx_final_exit_code",
        ):
            assert field in report, f"Missing field: {field}"

    def test_report_initial_exit_code_1_on_fallback(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_h_fail_then_success)
        report = yaml.safe_load(result.report_path.read_text())
        assert report["pdb2gmx_initial_attempt_exit_code"] == 1

    def test_report_fallback_command_contains_ignh(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_h_fail_then_success)
        report = yaml.safe_load(result.report_path.read_text())
        assert "-ignh" in (report.get("pdb2gmx_fallback_command") or "")

    def test_report_initial_command_lacks_ignh(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_h_fail_then_success)
        report = yaml.safe_load(result.report_path.read_text())
        assert "-ignh" not in (report.get("pdb2gmx_initial_command") or "")

    def test_report_final_exit_code_zero_on_fallback_success(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_h_fail_then_success)
        report = yaml.safe_load(result.report_path.read_text())
        assert report["pdb2gmx_final_exit_code"] == 0

    def test_report_initial_exit_code_zero_on_clean_success(self, tmp_path):
        result = self._run_assemble(tmp_path, self._pdb2gmx_clean_success)
        report = yaml.safe_load(result.report_path.read_text())
        assert report["pdb2gmx_initial_attempt_exit_code"] == 0
        assert report["pdb2gmx_fallback_used"] is False
