#!/bin/bash
# ─── Membrane embedding — InflateGRO shrink loop ──────────────────────────────
# Generated by EmbeddingBuilder. Do not edit manually.
#
# Physical target: APL ≤ 66.0 Å² (DPP, 64 + 2 Å² tolerance)
# Convergence: iterative deflation (factor 0.95) until APL converges.
# Telemetry: shrink_telemetry.json — one entry per iteration.
#
set -e
cd "$(dirname "$0")"

INFLATEGRO="inflategro-Jorge.pl"
INPUT_GRO="../03_embed_in_bilayer/system.gro"
TOPOL="../04_generate_topology/topol.top"
LIPID="DPP"
INFLATE=4.0
DEFLATE=0.95
APL_TARGET=66.0
MAX_ITER=200
GRIDSIZE=5
CUTOFF=0.0

# ── Python helper: read APL in Å² from area_2.dat ────────────────────────────
read_apl() {
    python3 -c "
import sys
try:
    val = float(open('area_2.dat').read().strip())
    print(int(val * 100))
except Exception as e:
    print(0)
    sys.exit(1)
"
}

# ── Python helper: append one iteration to shrink_telemetry.json ─────────────
log_iter() {
    local iter=$1 apl=$2 converged=$3
    python3 -c "
import json, pathlib, datetime
p = pathlib.Path('shrink_telemetry.json')
data = json.loads(p.read_text()) if p.exists() else {'iterations': [], 'converged': False, 'started_at': '$( date -Iseconds )'}
data['iterations'].append({'iter': $iter, 'apl_ang2': $apl, 'converged': $converged == 'true'})
data['last_apl_ang2'] = $apl
p.write_text(json.dumps(data, indent=2))
"
}

finalize_telemetry() {
    local apl=$1 converged=$2 n_iter=$3
    python3 -c "
import json, pathlib, datetime
p = pathlib.Path('shrink_telemetry.json')
data = json.loads(p.read_text()) if p.exists() else {'iterations': []}
data['converged'] = $converged == 'true'
data['final_apl_ang2'] = $apl
data['n_iterations'] = $n_iter
data['finished_at'] = datetime.datetime.now().isoformat(timespec='seconds')
p.write_text(json.dumps(data, indent=2))
"
}

# ── Validate tools ────────────────────────────────────────────────────────────
if [ ! -f "$INFLATEGRO" ]; then
    echo "[embedding] ERROR: inflategro script not found: $INFLATEGRO"
    echo "[embedding] Set inflategro_script in your YAML config or copy the script here."
    exit 1
fi
if ! command -v perl &>/dev/null; then
    echo "[embedding] ERROR: perl not found on PATH"
    exit 1
fi
if ! command -v gmx &>/dev/null; then
    echo "[embedding] ERROR: gmx not found on PATH"
    exit 1
fi

echo "[embedding] Starting membrane embedding shrink loop"
echo "[embedding] Lipid: $LIPID  |  APL target: ≤ ${APL_TARGET} Å²  |  Max iterations: $MAX_ITER"

# ── Step 1: initial inflation ─────────────────────────────────────────────────
echo "[embedding] Step 1: inflating bilayer (factor $INFLATE)"
cp "$INPUT_GRO" work.gro

perl "$INFLATEGRO" work.gro $INFLATE $LIPID $CUTOFF inflated.gro $GRIDSIZE area_2.dat
APL=$(read_apl)
echo "[embedding] Post-inflation APL = ${APL} Å²"
log_iter 0 $APL false
cp inflated.gro work.gro

# ── Step 2: first minimization (inflated system) ──────────────────────────────
echo "[embedding] Step 2: initial minimization (inflated system)"
gmx grompp -f minim_shrink.mdp -c work.gro -r work.gro -p "$TOPOL" -o work.tpr -maxwarn 2 -quiet
gmx mdrun -s work.tpr -deffnm work -nb gpu -quiet
cp work.gro work_prev.gro

# ── Step 3: shrink loop ───────────────────────────────────────────────────────
echo "[embedding] Step 3: shrink loop (deflate $DEFLATE per iteration)"
ITER=1
APL=$( python3 -c "print(int(float(open('area_2.dat').read().strip()) * 100))" )

while [ "$APL" -gt "$( python3 -c "print(int($APL_TARGET))" )" ] && [ "$ITER" -le "$MAX_ITER" ]; do

    echo "[embedding] Iter $ITER: APL = ${APL} Å² > ${APL_TARGET} Å² — deflating"

    perl "$INFLATEGRO" work.gro $DEFLATE $LIPID 0 work.gro $GRIDSIZE area_2.dat
    APL=$(read_apl)
    log_iter $ITER $APL false

    gmx grompp -f minim_shrink.mdp -c work.gro -r work.gro -p "$TOPOL" -o work.tpr -maxwarn 2 -quiet
    gmx mdrun -s work.tpr -deffnm work -nb gpu -quiet

    # Clean GROMACS backup files
    rm -f \#*

    ITER=$(( ITER + 1 ))
done

# ── Step 4: check convergence ─────────────────────────────────────────────────
APL=$(read_apl)
log_iter $ITER $APL true

if [ "$APL" -le "$( python3 -c "print(int($APL_TARGET))" )" ]; then
    echo "[embedding] CONVERGED at iter $ITER: APL = ${APL} Å² ≤ ${APL_TARGET} Å²"
    CONVERGED=true
else
    echo "[embedding] WARNING: did not converge after $MAX_ITER iterations (APL = ${APL} Å²)"
    CONVERGED=false
fi

# ── Step 5: final minimization on converged system ────────────────────────────
echo "[embedding] Step 5: final minimization"
gmx grompp -f minim_shrink.mdp -c work.gro -r work.gro -p "$TOPOL" -o final.tpr -maxwarn 2 -quiet
gmx mdrun -s final.tpr -deffnm final_shrink -nb gpu -quiet
rm -f \#*

# ── Step 6: write canonical output ───────────────────────────────────────────
cp final_shrink.gro converged.gro
finalize_telemetry $APL $CONVERGED $ITER

echo "[embedding] Done. Output: converged.gro  |  APL = ${APL} Å²  |  Iterations: $ITER"

if [ "$CONVERGED" = false ]; then
    echo "[embedding] HINT: APL did not reach target. Try increasing inflate_factor (current: $INFLATE)."
    exit 1
fi
